### ISSUE TITLE
Compile errors： /usr/include/boost/smart_ptr/shared_ptr.hpp(439): note: this candidate was rejected because mismatch in count of arguments       shared_ptr( shared_ptr<Y> const & r, element_type * p ) BOOST_NOEXCEPT : px( p ), pn( r.pn )

### ISSUE THREAD

**Issue by wuzhijiexia** [intel/caffe#102]
Follow error messages:

![image 2](https://user-images.githubusercontent.com/19603119/28257136-f97537ba-6afa-11e7-929d-272939fa9bcb.png)

Which version do we need for boost?

**Comment by guomingz** [comment]
Please try the boost version 1.46 or later.

**Comment by wuzhijiexia** [comment]
Thanks you very much!
