### ISSUE TITLE
How can I get a Windows version mklml?

### ISSUE THREAD

**Issue by adhere** [intel/caffe#108]
I test "Intel® Distribution of Caffe" on Ubuntu 14.04 with "Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz" and "Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz", both 3X faster than the office version caffe(with openblas). So I strongly want to use Intel Caffe on Windows(I have a windows CPU ONYL caffe forward program). I see this [Can I build this intel caffe on Windows OS?](https://github.com/intel/caffe/issues/59) and this [Installation](https://github.com/intel/caffe/wiki/Installation), so I know I need to that by myself. 

The [mkl-dnn](https://github.com/01org/mkl-dnn) is open source and no need mlsl. so that is miss mklml Windows version only. I download the [mkl-windows](http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/11564/w_mkl_2017.3.210.exe) and install. But I find the mklml, where is it? Can I get one? thanks!

**Comment by jgong5** [comment]
mklml does not support Windows right now. The Windows support is under plan. Please stay tuned. For now, you probably have to install a VM in order to use optimized IntelCaffe. BTW, the expected speedup should be far better than 3X. Please make sure you are using MKL2017 as the default engine via "-engine MKL2017" option. If you are using the latest IntelCaffe, that would be set automatically for you.

**Comment by hshen14** [comment]
https://github.com/01org/mkl-dnn/releases/download/v0.9/mklml_win_2018.0.20170720.zip

**Comment by adhere** [comment]
@jgong5 Oh， what a pity！ Installing a VM will be a bad idea for me， because the model I am using in Windows is embedded in the Windows Application. 
The Windows Version, probably when it can be released? 
I am using the latest IntelCaffe(Just clone from GitHub yesterday). I test some other model,  just like [MTCNN_Caffe](https://github.com/DaFuCoding/MTCNN_Caffe) can speed up more than 3X, almost up to 8X. But my private model can only speedup 3X.
Thanks @hshen14 @jgong5 ! Thank you for your help， thank you for your great work!

**Comment by whria78** [comment]
I succeed to install intel caffe on windows subsystem linux (WSL). It works well

**Comment by jgong5** [comment]
Glad to hear that!
