### ISSUE TITLE
concat layer error

### ISSUE THREAD

**Issue by heagoo** [intel/caffe#11]
encountered following error if we have 6 bottoms in concat layer (prototxt of the Concat layer attached). 

F1026 07:00:42.535639 14448 mkl_concat_layer.cpp:153] Check failed: e == E_SUCCESS (-1 vs. 0)
**\* Check failure stack trace: ***
    @     0x7f94bf66ee6d  (unknown)
    @     0x7f94bf670ced  (unknown)
    @     0x7f94bf66ea5c  (unknown)
    @     0x7f94bf67163e  (unknown)
    @     0x7f94bfb7b144  caffe::MKLConcatLayer<>::Forward_cpu()
    @     0x7f94bfc63262  caffe::Net<>::ForwardFromTo()
    @     0x7f94bfc634b5  caffe::Net<>::Forward()
    @     0x7f94c643e688  Detector::Detect()
    @     0x7f94c643c3b9  main
    @     0x7f94bbe45b15  __libc_start_main
@     0x7f94c643d4f5  (unknown)

layer {
  name: "mbox_loc"
  type: "Concat"
  bottom: "conv4_3_norm_mbox_loc_flat"
  bottom: "fc7_mbox_loc_flat"
  bottom: "conv6_2_mbox_loc_flat"
  bottom: "conv7_2_mbox_loc_flat"
  bottom: "conv8_2_mbox_loc_flat"
  bottom: "pool6_mbox_loc_flat"
  top: "mbox_loc"
  concat_param {
    axis: 1
  }
}

**Comment by pnoga** [comment]
Thank you for your sighting. We are in process of refactoring concat layer so we will search for solution for this problem.
