### ISSUE TITLE
Can not download the file mklml_lnx_2018.0.20170425.tgz 

### ISSUE THREAD

**Issue by cjliux** [intel/caffe#111]
I am currently trying to build the newest version of intel caffe, but one thing that's buffling me is that the file, mklml_lnx_2018.0.20170425.tgz, can not be downloaded, and every time I try there is the prompt, 'Connection reset by peer' or 'gzip: stdin: unexpected end of file', that requires me to retry.
I need some helps.

**Comment by teabottle300ml** [comment]
Hello, I faced the same problem.  If your network state is not very good, I suggest you downloading this package in browser and unpack it in <the path of your intel caffe>/external/mkl, and the shell prepare_mkl.sh in this path will not download this package again. The latest version of the package is 2018.0.20170720, please keep the version the same as that in prepare_mkl.sh, or the shell will download the latest version again.

**Comment by cjliux** [comment]
Thank you very much!

**Comment by hshen14** [comment]
Please specify the proxy if you cannot access the download link.
