### ISSUE TITLE
how to create trainval.txt, test.txt, and test_name_size.txt in data/VOC0712/

### ISSUE THREAD

**Issue by sreevasu** [intel/caffe#113]
HI,

any one can send trainval.txt, test.txt, and test_name_size.txt  files for VOC0712 data or 

can send VOC0712_trainval_lmdb and VOC0712_test_lmdb files

**Comment by etaf** [comment]
Hi, please refer to the [wiki](https://github.com/intel/caffe/wiki/SSD:-Single-Shot-MultiBox-Detector) .
