### ISSUE TITLE
Problems with protobuf simbols

### ISSUE THREAD

**Issue by jmourino** [intel/caffe#114]
Hi,
I am trying to compile the intel version of caffe.
Te compilation of pycaffe ends succesfully, but when I try to use in pyton, this is the result:

 python -c "import caffe"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "caffe/__init__.py", line 37, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "caffe/pycaffe.py", line 49, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /opt/cesga/caffe-intel/intelcaffe/build/lib/libcaffe.so.1.0.0-rc3: undefined symbol: _ZTIN6google8protobuf7MessageE

I am using intel caffe downloadad Sept 06th and protobuf 3.0.0

Regards,

Carlos

**Comment by ftian1** [comment]
could you please dump the libcaffe.so.1.0.0-rc3 shared library to see if libprotobuf.so.x is in use by running "readelf -a libcaffe.so.1.0.0-rc3 | grep Shared"?

**Comment by jmourino** [comment]
It seenms libprotobuf is not in use:

$ readelf -a libcaffe.so.1.0.0-rc3 | grep Shared
   Type:                              DYN (Shared object file)
  0x0000000000000001 (NEEDED)             Shared library: 
[libboost_system.so.1.60.0]
  0x0000000000000001 (NEEDED)             Shared library: 
[libboost_thread.so.1.60.0]
  0x0000000000000001 (NEEDED)             Shared library: 
[libboost_filesystem.so.1.60.0]
  0x0000000000000001 (NEEDED)             Shared library: 
[libboost_regex.so.1.60.0]
  0x0000000000000001 (NEEDED)             Shared library: 
[libboost_chrono.so.1.60.0]
  0x0000000000000001 (NEEDED)             Shared library: 
[libboost_date_time.so.1.60.0]
  0x0000000000000001 (NEEDED)             Shared library: 
[libboost_atomic.so.1.60.0]
  0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
  0x0000000000000001 (NEEDED)             Shared library: [libhdf5_cpp.so.7]
  0x0000000000000001 (NEEDED)             Shared library: [libhdf5.so.7]
  0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
  0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
  0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
  0x0000000000000001 (NEEDED)             Shared library: 
[libhdf5_hl_cpp.so.7]
  0x0000000000000001 (NEEDED)             Shared library: [libhdf5_hl.so.7]
  0x0000000000000001 (NEEDED)             Shared library: [libmlsl.so.1]
  0x0000000000000001 (NEEDED)             Shared library: 
[libmklml_intel.so]
  0x0000000000000001 (NEEDED)             Shared library: [libiomp5.so]
  0x0000000000000001 (NEEDED)             Shared library: [libmkldnn.so.0]
  0x0000000000000001 (NEEDED)             Shared library: 
[libpython2.7.so.1.0]
  0x0000000000000001 (NEEDED)             Shared library: 
[libboost_python.so.1.60.0]
  0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
  0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
  0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
  0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
   3142: 00000000004e01f0   162 FUNC    GLOBAL DEFAULT   10 
_ZN5caffe5Datum10SharedDt
   4383: 00000000004e0120   199 FUNC    GLOBAL DEFAULT   10 
_ZN5caffe5Datum10SharedCt
   4953: 00000000004e1390     2 FUNC    GLOBAL DEFAULT   10 
_ZN5caffe7Sampler10Shared
  13819: 00000000004e1320    26 FUNC    GLOBAL DEFAULT   10 
_ZN5caffe7Sampler10Shared
   6064: 00000000004e01f0   162 FUNC    GLOBAL DEFAULT   10 
_ZN5caffe5Datum10SharedDt
   7305: 00000000004e0120   199 FUNC    GLOBAL DEFAULT   10 
_ZN5caffe5Datum10SharedCt
   7875: 00000000004e1390     2 FUNC    GLOBAL DEFAULT   10 
_ZN5caffe7Sampler10Shared
  16741: 00000000004e1320    26 FUNC    GLOBAL DEFAULT   10 
_ZN5caffe7Sampler10Shared
$


But it was in library path both during compilation and now during execution.

Carlos

**Comment by ftian1** [comment]
usually it means somehow your env installed a old or 32bit libprotobuf.xxx.a in other places and the build system uses the wrong static lib rather the correct shared lib...

**Comment by jmourino** [comment]
Hi again,

Thank you very much. I couldn't realize which protobuf was linking to. 
But I have forced thee one I wanted with the -DProtobuf_LIBRARY variable 
and now it works.

Carlos

**Comment by ftian1** [comment]
issue has been solved. close #114
