### ISSUE TITLE
How to add custome layers?

### ISSUE THREAD

**Issue by wzbazinga** [intel/caffe#118]
I want to add a new layer to intel caffe. Is mkl implementation of the layer needed?

**Comment by ftian1** [comment]
no, it's not mandatory. 

you can implement a new layer without using MKL DNN primitives, such as prelu_layer. 

the MKL implementation of a layer is used to boost up the performance compared with caffe implementation, such as mkl_convolution_layer and conv_layer. the run-time choose on which one to be used is decided in layer_factory.cpp. you can dig into it.

**Comment by wzbazinga** [comment]
Thank you very much!
