### ISSUE TITLE
dilation not supported in MKLConvolutionLayer

### ISSUE THREAD

**Issue by heagoo** [intel/caffe#12]
It will report such error:
F1101 09:08:47.481178 131136 mkl_convolution_layer.cpp:369] Check failed: top[0]->width() == ow && top[0]->height() == oh && top[0]->channels() == oc*g && top[0]->num() == n Inclompatible shape of bottom with layer
if dilation is contained in conv layer.

And also a typo: should be "Inclompatible shape of **top** with layer"

**Comment by jczaja** [comment]
Thanks very much for reporting the problems. We will look to fixing them very soon. Currently you could extend your model params with : engine: CAFFE for layers using dilation to have them executed by CAFFE engine.
