### ISSUE TITLE
data augmentation stopped?

### ISSUE THREAD

**Issue by fastalgo** [intel/caffe#122]
I'm using the example of multinode/resnet_50_256_nodes_8k_batch

However, it always stopped here and stopped doing anything:

I0927 07:37:34.337448 145958 layer_factory.hpp:114] Creating layer data
I0927 07:37:34.337689 145958 net.cpp:218] Creating Layer data
I0927 07:37:34.337752 145958 net.cpp:871] data -> data
I0927 07:37:34.337836 145958 net.cpp:871] data -> label

What is the reason? How can I solve this problem?

**Comment by hshen14** [comment]
What's your running environment? Did you configure mpi environment well?

**Comment by fastalgo** [comment]
problem solved, thanks!
