### ISSUE TITLE
MPI or MLSL

### ISSUE THREAD

**Issue by fastalgo** [intel/caffe#124]
I compiled the Intel Caffe 1.0.3 with MPI (not MLSL).

Then I ran the multinode/resnet_50_256_nodes_8k_batch example for 5 epochs (800 iterations)

I only got 0% accuracy. I think the result is wrong. 

What is the reason? Because of MPI?

**Comment by fzou1** [comment]
Did you change anything in intel caffe? Do you mind send it to me?

**Comment by fastalgo** [comment]
Already solved this problem. Thanks!
