### ISSUE TITLE
AlexNet Prototxt Validation vs Testing

### ISSUE THREAD

**Issue by PatilChetan** [intel/caffe#128]
For [AlexNet](https://github.com/intel/caffe/blob/master/models/bvlc_alexnet/train_val.prototxt) Prototxt , why network is using validation (ilsvrc12_val_lmdb) image during testing phase?

Valid for [AlexNet in Intel Optimized Model](https://github.com/intel/caffe/blob/master/models/intel_optimized_models/alexnet/train_val.prototxt) too.

**Comment by jgong5** [comment]
The configuration is the same as BVLC Caffe. You may modify the prototxt to use test dataset if needed.

**Comment by PatilChetan** [comment]
I understand it's coming from BVLC Caffe and Intel borrowed most of the code and examples. For new user it's confusing. As testing and training data set is used during training, while validation is blind data to trained model.

Also, the [step where LMDB](https://github.com/intel/caffe/blob/master/examples/imagenet/create_imagenet.sh) is created also shows in correct code of using validation images of ImageNet rather than testing.

**Comment by jgong5** [comment]
The validation dataset is used to check the health of the training. May I know what particular problem you are concerned with?

**Comment by PatilChetan** [comment]
@jgong5 

I am confused. For ImageNet data set, there are three types of sub data:

1) Training
2) Testing
3) Validation

Isn't (1) and (2) used during training model with Caffe? Validation (2) is used during deployment or to check if the model is working accurately or not _after_ it has been trained?

If yes, then both in create_imagenet.sh and train_val.prototxt, testing data along with training data should be used. It seems, validation is being used instead of testing data?

**Comment by jgong5** [comment]
(1) is used in training and (3) is used in testing. We are not using (2).

**Comment by PatilChetan** [comment]
@jgong5 

Ok. Is this case specific or applies to all networks using ImageNet data set?

**Comment by jgong5** [comment]
I believe it is the best practice for all networks.
