### ISSUE TITLE
VGGNet

### ISSUE THREAD

**Issue by PatilChetan** [intel/caffe#129]
There are multiple training and solver file for VGGNet [here](https://github.com/intel/caffe/tree/master/models/intel_optimized_models/ssd/VGGNet).

Can anyone please share which one to use?

**Comment by ftian1** [comment]
It depends on your purpose. you want to use it on VOC dataset or COCO dataset?

**Comment by PatilChetan** [comment]
@ftian1 

I want to keep ImageNet dataset for any network I will train. Is this not a good idea?

**Comment by ftian1** [comment]
SSD is using VGG16 as base network, which is pretrained on ILSVRC dataset. You just need fine-tune it on your new dataset.

As for using which topology under COCO or VOC directory, it depends on your new dataset. the topology in COCO dir was designed for small objects compared with VOC dataset. so if your new dataset contains many small objects, it should be better I guess. But according to SSD paper(https://arxiv.org/abs/1512.02325),  it shows SSD is a general framework for high quality real-time detection (see this paper section 3.5). From this view, they should have no big difference. Anyway that's what you need to dig into if you want to take a data scientist role:)
