### ISSUE TITLE
Decision Criteria of Intel Caffe To Distribute Threads To Cores

### ISSUE THREAD

**Issue by PatilChetan** [intel/caffe#130]
Hi All,

Is there a specific algorithm or approach followed by Intel Caffe in terms of threads to spawn, how and where to map it on the architecture? Does it depend on the network architecture being run?

Any possible documentation I can read apart from the code? As far as I understand, only layer section of the code is threaded?

Thanks.

**Comment by hshen14** [comment]
Please refer to some code pieces in cpu_info.cpp.

**Comment by hshen14** [comment]
Close it due to no activities in recent month. Please feel free to reopen it.
