### ISSUE TITLE
why the intel caffe need so much memory ?

### ISSUE THREAD

**Issue by daicoolb** [intel/caffe#131]
We test FCN in phi node (68cores).

We find with engine MKL 2017 it needs almost all of the memory up to 94.3G.

We have disabled the numa configuration and other recommendations with the wiki.

At the same time. we have tested the engine CAFFE with FCN, it only needs 24G memory, why ?

**Comment by etaf** [comment]
Hi, @daicoolb  is the problem still there?

**Comment by daicoolb** [comment]
yes,  I it is not solved now.

**Comment by ftian1** [comment]
MKL2017 reorders the input data format from nchw to other formats which could be leveraged by AVX2/AVX512 instructions. this behavior will increase the memory consumption.
