### ISSUE TITLE
why the benchmark  in Centos and Ubuntu are different?

### ISSUE THREAD

**Issue by daicoolb** [intel/caffe#132]
**This is the record in CentOS**
Topology: alexnet
Cpu model :             Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz

CPUs with optimal settings:
    Intel Xeon E5-26xx (Broadwell)
    Intel Xeon Phi 72xx (Knight Landing)
    Intel Xeon Platinum 8180 (Skylake)
    Intel Xeon 6148 (Skylake)

Settings:
    Host file: 
    Running mode: time
    Benchmark: none
    Debug option: off
    Engine: MKL2017
    Number of MLSL servers: -1
        -1: selected automatically according to CPU model.
            BDW/SKX: 2, KNL: 4
    Iteration for running caffe time: 5
    Model file for running caffe time: models/intel_optimized_models/alexnet/knl/train_val_dummydata.prototxt
    Network: opa
    Number of nodes: 1
Cache mode.

real	0m12.306s
user	7m58.840s
sys	0m21.664s
batch size : 256
average time : 575.8 ms
benchmark speed : 444 images/s
Result folder: /home/liujie/caffe/result-20171020152148

**This is the record in Ubuntu**
Topology: alexnet
Cpu model :             Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz

CPUs with optimal settings:
    Intel Xeon E5-26xx (Broadwell)
    Intel Xeon Phi 72xx (Knight Landing)
    Intel Xeon Platinum 8180 (Skylake)
    Intel Xeon 6148 (Skylake)

Settings:
    Host file: 
    Running mode: time
    Benchmark: none
    Debug option: off
    Engine: MKL2017
    Number of MLSL servers: -1
        -1: selected automatically according to CPU model.
            BDW/SKX: 2, KNL: 4
    Iteration for running caffe time: 5
    Model file for running caffe time: models/intel_optimized_models/alexnet/knl/train_val_dummydata.prototxt
    Network: opa
    Number of nodes: 1
Cache mode.
Warning: cannot find sensors

real	0m12.915s
user	4m51.531s
sys	0m8.075s
batch size : 256
average time : 331.2 ms
benchmark speed : 772 images/s

**Comment by guomingz** [comment]
Suggest to increase the caffe time iterations from 5 to 100. 
You may also need to clear the system cache with `
 sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'
`

**Comment by daicoolb** [comment]
It can not solve my problem

**Comment by manofmountain** [comment]
Intelcaffe have new release 1.0.5 and some changes happened within the 'run_benchmark.sh' script. you might take a new try on CentOS.
Under CentOS 7.2, i obtain around 800 images / sec with a 'Xeon Phi 7250'.
