### ISSUE TITLE
BatchNorm Forward pass creation gets SIGSEGV

### ISSUE THREAD

**Issue by manoharks** [intel/caffe#134]
## Setup
Ubuntu 16.04 
Intel Caffe and dependencies installed using prepare_env.sh
Tried to train network with the following command and train.prototxt causes Segmentation Fault:

```
$ caffe-intel/build/tools/caffe train -solver ./solver.prototxt > output.txt
```

```
I1023 11:33:41.247819 74212 caffe.cpp:329] Starting Optimization
I1023 11:33:41.247824 74212 solver.cpp:559] Solving MobileNet-SSD
I1023 11:33:41.247826 74212 solver.cpp:560] Learning Rate Policy: multistep
*** Aborted at 1508783622 (unix time) try "date -d @1508783622" if you are using GNU date ***
PC: @     0x7efed8b04786 (unknown)
*** SIGSEGV (@0x5563dd2a1488) received by PID 74212 (TID 0x7efedae00ac0) from PID 18446744073125106824; stack trace: ***
    @     0x7efed8ab74b0 (unknown)
    @     0x7efed8b04786 (unknown)
    @     0x7efed8b06184 __libc_malloc
    @     0x7efed244c7b3 mkl_serv_malloc
    @     0x7efed10f27cc mkl_dnn_avx512_Xbyak_F32::LabelManager::defineSlabel()
    @     0x7efed283bceb (anonymous namespace)::mkl_dnn_avx512_jit_bnorm_F32::compute_mean_variance()
    @     0x7efed284918d (anonymous namespace)::mkl_dnn_avx512_jit_bnorm_F32::mkl_dnn_avx512_jit_bnorm_F32()
    @     0x7efed2834dc7 mkl_dnn_avx512_createJITBnorm_F32
    @     0x7efed280f9ea mkl_dnn_avx512_bkdJITBatchNormalization_F32
    @     0x7efed10a559d mkl_dnn_avx512_BatchNormalizationCreateForward_v2_F32
    @     0x7efeda3776da caffe::MKLBatchNormLayer<>::ForwardStatsBatch_cpu()
    @     0x7efeda3782a3 caffe::MKLBatchNormLayer<>::Forward_cpu()
    @     0x7efeda311c92 caffe::Net<>::ForwardFromTo()
    @     0x7efeda311ea7 caffe::Net<>::Forward()
    @     0x7efeda1e4a24 caffe::Solver<>::ForwardBackward()
    @     0x7efeda1f3c31 caffe::Solver<>::Step()
    @     0x7efeda1f465e caffe::Solver<>::Solve()
    @     0x5563d44080e3 train()
    @     0x5563d43ffd6f main 
    @     0x7efed8aa2830 __libc_start_main
    @     0x5563d4400929 _start
    @                0x0 (unknown)
```
Complete output (output.txt), solver (solver.prototxt) and model (train.prototxt) attached.
[output.txt](https://github.com/intel/caffe/files/1408415/output.txt)
[solver.prototxt.txt](https://github.com/intel/caffe/files/1408421/solver.prototxt.txt)
[train.prototxt.txt](https://github.com/intel/caffe/files/1408422/train.prototxt.txt)

**Comment by guomingz** [comment]
Hi @manoharks, 
Would  you please upload the **test.prototxt** which declared in the solve.prototxt `test_net: "test.prototxt"` ?

**Comment by manoharks** [comment]
@guomingz test.prototxt attached below:
[test.prototxt.txt](https://github.com/intel/caffe/files/1415518/test.prototxt.txt)

**Comment by guomingz** [comment]
@manoharks hi, we tried to reproduce this issue with the 1.0.6 release but we didn't found the BN fwd issue. We got another issue which it seems to the  specific setting on your side. Would u please have a try again with the 1.0.6 release? If u couldn't train this topology on your side, please let us know.

**Comment by manoharks** [comment]
Couldn't reproduce. Might have been a configuration issue (and lost track of the configuration). Will keep a watch out for the issue in the future. Closing the bug meanwhile.
