### ISSUE TITLE
nd pooling with mklpooling

### ISSUE THREAD

**Issue by NonvolatileMemory** [intel/caffe#137]
if i use 3d pooling layer with engine: CAFFE there will be no problem ,but if i don't set this para there will be a bug,I guess may be because of the mklpooling layer

**Comment by ftian1** [comment]
MKL engine doesn't provide such 3D pooling primitive. so intel caffe also has no such feature.

**Comment by NonvolatileMemory** [comment]
thx for reply,please consider the pr[https://github.com/intel/caffe/pull/136](Add new example for C3D Network)

**Comment by NonvolatileMemory** [comment]
thx for reply!
https://github.com/intel/caffe/pull/136 but why my pr is still open and nobody care about it?
@ftian1

**Comment by hshen14** [comment]
Thanks for PR. Since the default engine is MKLDNN, we will put PR in our future support list.
