### ISSUE TITLE
What dependencies are different?

### ISSUE THREAD

**Issue by boaz001** [intel/caffe#14]
Where can I find more information on the added dependencies (compared to BVLC/caffe)?

I found that intel/caffe requires c++11? (at least; the flag `-std=c++11` is added in CMakeLists.txt)

**Comment by jreniecki** [comment]
MKL is set as a default BLAS library in [Makefile.config](https://github.com/intel/caffe/blob/master/Makefile.config.example) but you don't need to worry about it - required binary is downloaded automatically during compilation.

By comparing [Dockerfile](https://github.com/intel/caffe/blob/master/docker/standalone/cpu-ubuntu/Dockerfile) with the BVLC's one you can see that not much has been changed - other dependencies stays the same.
