### ISSUE TITLE
mkldnn_eltwise_layer.cpp Not Implemented Yet

### ISSUE THREAD

**Issue by kostinalexey** [intel/caffe#142]
Here is the log message
F1101 12:14:03.755115  6367 mkldnn_eltwise_layer.cpp:102] Not Implemented Yet

It looks as mkldnn_eltwise_layer is not ready

**Comment by kostinalexey** [comment]
If I set USE_MKL2017_AS_DEFAULT_ENGINE, then get this message

F1101 12:53:23.283581  9669 mkl_eltwise_layer.cpp:113] Check failed: this->layer_param().eltwise_param().operation() == EltwiseParameter_EltwiseOp_SUM MKLEltwise Layer only process summation.

Better to disable MKL and NKLDNN implementations of eltwise layer as it prohibits use of "maxout" and "resnet" DNNs in this fork of caffe

**Comment by ftian1** [comment]
You can choose Caffe implementation of eltwise layer by specifying CAFFE engine at the prototxt, something like:

layer {
  bottom: "xxx"
  bottom: "xxx"
  top: "xxxx"
  name: "xxxx"
  type: "Eltwise"
  eltwise_param {

  }
+  engine: "CAFFE"  
}

**Comment by kostinalexey** [comment]
Though it is good work around for the new models it is not practical for production case where it is not easy to change deployed models. I found it easier just to comment out relevant lines in the layer_factory.cpp

**Comment by ftian1** [comment]
shouldn't they, updating deployed models or updating caffe binary,  be same effort?

**Comment by kostinalexey** [comment]
@ftian1 The amount of effort is not relevant to the issue and there other good reasons not to modify model files just because of particular computation library (Intel for of caffe in this case)

The reason I submitted the issue is for you to know there is a problem with particular layer so you can improve your fork of Caffe.

**Comment by hshen14** [comment]
Only sum is supported in MKL-DNN now. Close it first.
