### ISSUE TITLE
Does not build with CUDA 9 + CUDNN 7

### ISSUE THREAD

**Issue by kostinalexey** [intel/caffe#143]

**Comment by guomingz** [comment]
Hi kostinalexey, 

This fork is dedicated to improving Caffe performance when running on Intel CPU. Would u please try it on the CPU? 

Thanks.

**Comment by kostinalexey** [comment]
Hi,

I did try running it on CPU and so far in my tests it is about 2x faster than BVLC Caffe with MKL.

However lack of support of modern Cuda makes it difficult to use this fork for production environment where the library needs to use GPU when possible and CPU if GPU is not available.

Best regards
Alexey

**Comment by soulslicer** [comment]
Has this been resolved?
