### ISSUE TITLE
No cmake option for MKLROOT

### ISSUE THREAD

**Issue by kostinalexey** [intel/caffe#144]
I am building caffe as cmake External_Project. Would be good to have option (MKLROOT or INTELROOT) to pass to cmake call. 

Setting $MKLROOT environment variable is not cmake friendly

**Comment by ftian1** [comment]
@kostinalexey I agree it would be more clean from CMake style view. but $MKLROOT or $MKLDNNROOT env variables are only used if user want to specify a special version of them. in default build, they will not be used. And as they are widely used in BVLC caffe/Intel Caffe/MKLDNN project, we will list this as low priority task and not prefer to change this now.
