### ISSUE TITLE
Protobuf is not compatible with BVLC caffe

### ISSUE THREAD

**Issue by kostinalexey** [intel/caffe#145]
IDs used in caffe.proto differ from https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto

Making existing models not compatible

In particular PoolingParameter
here   
repeated uint32 pad = 2; 
repeated uint32 stride = 4;
in BVLC
optional uint32 pad = 4 [default = 0];

As result "stride" in BVLC is treated as "pad" in Intel

**Comment by ftian1** [comment]
Hi, could you pls let me know what's the impact of this mismatch?

**Comment by kostinalexey** [comment]
See the last sentence in my original post "As result "stride" in BVLC is treated as "pad" in Intel"

To give you an example. Say you have 
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "eltwise1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
in the models produced by BVLC caffe
When loaded into Intel caffe you will get
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "eltwise1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    pad: 2
  }
}
Which not only has completely different meaning it would just simple fail check pooling_layer.cpp:145
CHECK_LT(pad_h_, kernel_h_);
CHECK_LT(pad_w_, kernel_w_);

**Comment by ftian1** [comment]
I saw your last sentence, but I don't understand why it's problem. 

The tag field number is only seen at the proto definition file and be used to identify item in binary stream encoding. But when parsing a model prototxt file passing down by user, the protobuf parser only look the field name rather than tag number. 

do you come across a real case for such issue? if yes, could you share the reproduce steps?

**Comment by kostinalexey** [comment]
The reason this protobuf feature manifest itself here is that caffe model consists of 2 parts. The first is plain text based prototxt file, where indeed there is no problem with IDs (as they are not present there). The second part is binary file where all string labels replaced with the IDs and therefore values of IDs here are VERY important.

Now what you have with mixed IDs is txt file does not match binary one if the pair of files was generated by BVLC and read by Intel and vice versa.

I have the real case where this is exactly the issue, but unfortunately I can not share the model files. However I would expect this issue would manifest itself on any model which has pool layer with stride parameter (and would fail check on line 145 if kernel_size par == stride) I recommend taking, for example, this model from the caffe zoo https://gist.github.com/weiliu89/2ed6e13bfd5b57cf81d6

**Comment by etaf** [comment]
@kostinalexey so the issue only happens when you load bvlc-caffe pre-trained model using intel-caffe, right?

**Comment by ftian1** [comment]
@etaf we often do that. The pre-trained model includes weight/bias value rather than tag number.

@kostinalexey  Your model file is not necessary as we can find a similar one, but pls share us your detail reproduce steps.

**Comment by kostinalexey** [comment]
Hi, I found the source of the issue while trying to extract code sample for you. We use google::protobuf::Message::SerializeToOstream function to compress prototxt. So the problem was that compression was done with BLVC Caffe IDs and on the read caffe::NetParameter::ParseFromCodedStream was used which had Intel Caffe IDs. Basically it was problem in our code, not yours.

I am sorry for not discovering this earlier and distracting you.

I think the issue could be closed now.

**Comment by ftian1** [comment]
thanks for your info. @kostinalexey
