### ISSUE TITLE
MobileNet-SSD mkl_concat_layer failure

### ISSUE THREAD

**Issue by tbaker2** [intel/caffe#146]
I downloaded the MobileNet-SSD model, and weights for deploy from here: [https://github.com/chuanqi305/MobileNet-SSD](url).  When running the script demo.py I get the following crash report: 

> F1101 16:58:41.463665 20778 mkl_concat_layer.cpp:176] Check failed: e == E_SUCCESS (-1 vs. 0) 
> *** Check failure stack trace: ***
> Aborted (core dumped)

**Comment by ftian1** [comment]
Are you using latest release version? we have set MKLDNN as default engine, but looks you are still using MKL2017 engine.

could you please use latest code or try to add below

engine: "MKLDNN"

to the second line of MobileNetSSD_deploy.prototxt to see if MKLDNN engine has similar issue?

**Comment by tbaker2** [comment]
I was using version 1.03.  I just checked out the master, and changed the prototxt file as you recommended.  I got the same results with a little more information:
> F1101 18:20:23.701580 30673 mkldnn_concat_layer.cpp:63] Check failed: bottom[0]->height() == bottom[i]->height() (4332 vs. 2400) 
> *** Check failure stack trace: ***
> Aborted (core dumped)

**Comment by chandlerz** [comment]
I got the error "mkl_concat_layer.cpp:176] Check failed: e == E_SUCCESS (-1 vs. 0)" with the engine MKL2017 and the error "mkldnn_concat_layer.cpp:63] Check failed: bottom[0]->height() == bottom[i]->height() (4332 vs. 2400)" with the engine MKLDNN. 

Any clue to fix the issue?

**Comment by ftian1** [comment]
@chandlerz The issue has been root caused and will be solved at future release. 

you can specify CAFFE engine in all concat layers to workaround this issue.

or you can have a try below fix (pls change the .txt postfix to .patch and apply it).
[0001-concat-layer-fixes-for-SSD.txt](https://github.com/intel/caffe/files/1452184/0001-concat-layer-fixes-for-SSD.txt)

**Comment by chandlerz** [comment]
@ftian1 Thanks for your help. I succeeded to run the model after specifying all cancat layers to use the CAFFE engine. It seems Intel Caffe uses MKLDNN as the default engine.

BTW, have you tried the patch also?

**Comment by ftian1** [comment]
@chandlerz we have changed the default engine to MKLDNN at last release. As for the patch, sure, it's workable at my side.

**Comment by hshen14** [comment]
We released v1.1.0, please try it.
