### ISSUE TITLE
How to add new layer

### ISSUE THREAD

**Issue by qinxianyuzi** [intel/caffe#147]
Hi, I add tripletloss layer to  the intel-caffe.When building the caffe I get the following error report:
.build_release/lib/libcaffe.so: undefined reference to `caffe::TripletLossLayer<float>::Forward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&)

But I add  tripletloss layer to  the BVLC-caffe. I builded successfully.

**Comment by ftian1** [comment]
latest intel caffe sets CPU_ONLY = ON by default. Please ensure you add code like below.

#ifdef CPU_ONLY
STUB_GPU(MKLConvolutionLayer);
#else
template <typename Dtype>
void MKLConvolutionLayer<Dtype>::Forward_gpu(
    const vector<Blob<Dtype>*>& bottom, const vector<Blob<Dtype>*>& top)
  {NOT_IMPLEMENTED;}
template <typename Dtype>
void MKLConvolutionLayer<Dtype>::Backward_gpu(
    const vector<Blob<Dtype>*>& top, const vector<bool>& propagate_down,
    const vector<Blob<Dtype>*>& bottom)
  {NOT_IMPLEMENTED;}
#endif

**Comment by qinxianyuzi** [comment]
I have solved it. Thank you.
