### ISSUE TITLE
I can't find Scale layer in resnet-50

### ISSUE THREAD

**Issue by qinxianyuzi** [intel/caffe#148]
Hi, everyone: I have no idea why the intel optimized resnet50 can work without Scale layer. Can someone tell me why? Thanks!

**Comment by jgong5** [comment]
MKL-DNN's batch normalization primitive does the job of both normalization and scale-shift. The latter was Scale layer's job.

**Comment by ChongyuIntel** [comment]
Only run the model with pure CAFFE layer need to manually add the scale layer to the prototxt. If you run with MKL-DNN engine, the function of scale layer is merged into batch norm layer.

**Comment by hshen14** [comment]
Please try the solution suggested, running Caffe command with -engine MKLDNN
