### ISSUE TITLE
forward pass with different batch size segmentation fault

### ISSUE THREAD

**Issue by lolongcovas** [intel/caffe#150]
here an example of forward pass of different batch size, the results are a bit strange:

```
import caffe
import numpy as np
net = caffe.Net('models/bvlc_alexnet/deploy.prototxt', 'models/bvlc_alexnet/bvlc_alexnet.caffemodel', caffe.TEST)

X = np.random.randn(227, 227, 3).astype(np.float32)
for i in range(1, 11):
    inputs = np.array([X for _ in range(i)], np.float32).transpose([0, 3, 1, 2])
    print inputs.shape
    net.blobs['data'].reshape(*(inputs.shape))
    net.blobs['data'].data[...] = inputs[...]
    out = net.forward()['prob'].copy()
    print out.mean(0)
```

it raises a segmentation fault.

**Comment by ftian1** [comment]
it's the bug in mkldnn layers, which don't support reshape on different batch size. You can specify caffe engine as a workaround at first.

**Comment by lolongcovas** [comment]
thanks for the reply. Do you think this issue will be fixed in the next release?

**Comment by ftian1** [comment]
yes, it will be

**Comment by soulslicer** [comment]
May i ask when the next release may be

**Comment by ftian1** [comment]
1.1.0 release has been published. could you try this?

**Comment by soulslicer** [comment]
i just took the version from 2 weeks ago..when was this published??

**Comment by ftian1** [comment]
4 days ago

**Comment by soulslicer** [comment]
ah..i will update it and test. thank you. can i ask on the side if the opencl version running on an Intel chip / gpu could outperform the mkl version

**Comment by ftian1** [comment]
it mainly depends on the h/w you used as finally the TFLOPS of h/w and the computation throughput  of the topology you used decides the final result.

**Comment by soulslicer** [comment]
When will this be in the intel branch in caffe official?

**Comment by ftian1** [comment]
It has been there. They are same one, just different links.

**Comment by soulslicer** [comment]
Hey its still not working!

**Comment by ftian1** [comment]
@soulslicer are you sure? the code shared by lolongcovas works at my side with 1.1.0 release. could you paste your detail steps?

**Comment by soulslicer** [comment]
I am testing it on the latest master branch. should i be using the 1.1.0 release?

**Comment by ftian1** [comment]
that's not big deal. what are your steps?

**Comment by soulslicer** [comment]
I happen to be using the C++ API. If I keep my net size the same and I do forward passes, I get the correct result in my FCN. However, upon calling reshape to the input image size of my network, I get a blank output. Not sure why this is the case

**Comment by yflv-yanxia** [comment]
I have the same problem, any plans to fix it? @ftian1
