### ISSUE TITLE
Different algorithm of ROIPoolingLayer between CPU/GPU implementation?

### ISSUE THREAD

**Issue by nnop** [intel/caffe#153]
I had a look at the `ROIPoolingLayer` codes. The cpu implementation deals with 3D RoI pooling, while the gpu implementation is the same with Ross's original RoI pooling codes.

**Comment by ftian1** [comment]
yes, it's current status. we have no plan to support 3d roi pooling for gpu code.

**Comment by nnop** [comment]
Got it.
