### ISSUE TITLE
asynchronous SGD

### ISSUE THREAD

**Issue by fastalgo** [intel/caffe#157]
Does Intel Caffe still support asynchronous SGD?
If so, how to use it?

**Comment by fzou1** [comment]
Yes. I created a brief wiki for this feature: https://github.com/intel/caffe/wiki/Asynchronous-SGD-in-Intel-Caffe

**Comment by fastalgo** [comment]
Thanks so much!

**Comment by fzou1** [comment]
I'd like close this issue. Feel free to open another issue if you have any further questions.

**Comment by fastalgo** [comment]
I tried GoogleNet. 1 worker per group is fine. For example, if I have 17 machines, I will set it as one server and 16 groups. This setting work very well. If I set it to 4 groups, if will not work (unless I remove validation during training).
