### ISSUE TITLE
model_libs.py UnpackVariable assert len > 0

### ISSUE THREAD

**Issue by stavBodik** [intel/caffe#159]
Can anyone explain me this ?

inside model_libs.py there is function called UnpackVariable

the first row is assert len > 0

who,why,when,what is len ? len of what ? are you serious ? how can i debug code like this ?

In my case the assertion fails but idk what this means ? 

Is this type of checking if built in function "len" is null pointer ?

Thanks !

**Comment by guomingz** [comment]
Yes,It's a kind of checking on the built-in function `len`. 
You may replace the len to any other built-in fuction, e,g `abs`.

**Comment by stavBodik** [comment]
In which case built in function's of python can be null ?

**Comment by Hockery** [comment]
python 3 can't compare build-in with int, but python 2 is ok. 
I also encounter the error when run caffe-ssd.
