### ISSUE TITLE
Can I use MPI in the case of single node?

### ISSUE THREAD

**Issue by wuzhijiexia** [intel/caffe#16]
Can I use MPI in the case of single node? I do it but no effect. I hope to know the reason.

**Comment by uberloss** [comment]
Hi, could you give us a little more detail on what do you mean by no effect? Do you see any errors?

Make sure you have built caffe with mpi support (USE_MPI=1 flag) and add the `--param_server=mpi` parameter to the train command.

Have you tried to run the cifar10 example? https://github.com/intel/caffe/wiki/Multinode-cifar10
If you could attach any logs it would be helpful. You can get them i.e. by appending `2>&1 |  tee log.out` to the command you run .

**Comment by pnoga** [comment]
Do you need any additional help with this issue? Or can I close it?

**Comment by wuzhijiexia** [comment]
OK! You can close it.
