### ISSUE TITLE
3 Failed Tests - CompileNetTest

### ISSUE THREAD

**Issue by larryluo619** [intel/caffe#160]
I ran make runtest and encountered 3 failed test as below,

[----------] Global test environment tear-down
[==========] 1322 tests from 200 test cases ran. (135672 ms total)
[ PASSED ] 1319 tests.
[ FAILED ] 3 tests, listed below:
[ FAILED ] CompileNetTest.TestCompileNetLayerParamEngineConvolution
[ FAILED ] CompileNetTest.TestCompileNetBatchNormConvolution
[ FAILED ] CompileNetTest.TestCompileNetConvolution

3 FAILED TESTS
YOU HAVE 1 DISABLED TEST

Makefile:734: recipe for target 'runtest' failed
make: *** [runtest] Error 1

Anybody know this and have a solution?

Ubuntu 16.04
Python 2.7.12
Intel-caffe v1.0.7

**Comment by guomingz** [comment]
Hello @larryluo619 ， this issue will  be fixed in the 1.1.0 release. Thanks.

**Comment by hshen14** [comment]
Please check the issue with 1.1.0 release and raise it again if the issue was not resolved.
