### ISSUE TITLE
disable weight update

### ISSUE THREAD

**Issue by fastalgo** [intel/caffe#161]
In the past, I could disable weight update by using DISTR_WEIGHT_UPDATE

However,  DISTR_WEIGHT_UPDATE was removed at April 23rd: https://github.com/intel/caffe/commit/58fe50fdb6736b8f6fc47b5038ad4c323a78d677

Is it possible to disable weight update? I need to do some algorithm-level testings.

**Comment by fzou1** [comment]
Sorry. Do you mean you comment out some lines of code defined in this macro to disable weight update? The macro is not used for disabling weight update, right? 

apply_updates function in include/caffe/multinode/multi_sync.hpp, is used to update weights now. You can remove the function calls.

**Comment by fastalgo** [comment]
Thanks so much!

**Comment by fzou1** [comment]
You're welcome. Happy New Year! :-)
