### ISSUE TITLE
copy LMDB dataset to local memory

### ISSUE THREAD

**Issue by fastalgo** [intel/caffe#162]
We have a KNL cluster. Before staring the distributed training, we copied the LMDB dataset to every computational node (e.g. /dev/shm). Each node will get a copy of the LMDB dataset.

This works very well for ImageNet dataset.

However, when we use CIFAR-10 dataset, we got following error:

*** Error in `/scratch/00946/zzhang/skylake/caffe/caffe-intel-1.0.7/build/tools/caffe': double free or corruption (fasttop): 0x000055f2e0959f80 ***

**Comment by fastalgo** [comment]
BTW, I'm using this network: https://github.com/yihui-he/resnet-cifar10-caffe/blob/master/resnet-32/trainval.prototxt

Using other networks doesn't have this problem.

**Comment by chuanqi129** [comment]
Hi @fastalgo , I found the network have a issue in data layer.  
`layer {
  name: "data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
    scale: 0.0078125
    mirror: true
    crop_size: 32
    **mean_value: 128**
  }
  data_param {
    source: "cifar-10-batches-py/train"
    batch_size: 128
    backend: LMDB
  }
}
layer {
  name: "data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  transform_param {
    scale: 0.0078125
    **mean_value: 128**
  }
  data_param {
    source: "cifar-10-batches-py/test"
    batch_size: 128
    backend: LMDB
  }
}`
If we use  3 channel data, we should add three `mean_value` in the data layer. Could you please check again? In this way, the issue gone away in my sides.

**Comment by fastalgo** [comment]
Thanks so much!

**Comment by chuanqi129** [comment]
@fastalgo You're welcome. Actually, the root cause of this issue is multi-thread modify the `mean_values_` vector in `src/caffe/data_transfomer.cpp` file. We have fixed it, and will update it in the future release.

**Comment by hshen14** [comment]
It is fixed in internal release and publish to external soon.
