### ISSUE TITLE
Changing OpenMP thread counts makes no difference

### ISSUE THREAD

**Issue by soulslicer** [intel/caffe#165]
I am currently trying a few nets with this version of Caffe. Unfortunately, while it is almost 10 times faster than the normal CPU version of Caffe, changing the numbers of openmp threads does not make a difference

It seems to use more cores, and more memory, but the runtime stays the same; I have tried playing around with the following options and the runtime for a forward pass is always the same:
```

  591  export MKL_NUM_THREADS="2"
  592  export MKL_DOMAIN_NUM_THREADS="MKL_BLAS=2"
  593  export OMP_NUM_THREADS="1"
  594  export MKL_DYNAMIC="FALSE"
  595  export OMP_DYNAMIC="FALSE"
```

I am currently compiling this with gcc 5.4

**Comment by hshen14** [comment]
Would you please list HW configurations?

**Comment by soulslicer** [comment]
I have 64GB of Ram
Processor: model name	: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
Ubuntu 16.04 - g++ 5.4

**Comment by soulslicer** [comment]
My bad..it is because of memory pressure. It starts going into swap space if i exceed 8 cores. but before that performance does increase
