### ISSUE TITLE
3 Failed Tests - CompileNetTest

### ISSUE THREAD

**Issue by JohnSmithyy** [intel/caffe#166]
I ran sudo make runtest and encountered the following 3 failed tests:

[ FAILED ] 3 tests, listed below:
[ FAILED ] CompileNetTest.TestCompileNetLayerParamEngineConvolution
[ FAILED ] CompileNetTest.TestCompileNetConvolution
[ FAILED ] CompileNetTest.TestCompileNetBatchNormConvolution

How do I go about to resolving this?

I'm on Ubuntu 16.04 and Python 2.7.12.

**Comment by guomingz** [comment]
Hi @JohnSmithyy  Have u tried the latest release(1.1.0)? This is a known issue and we resolved it in 1.1.0

**Comment by ChongyuIntel** [comment]
[----------] Global test environment tear-down
[==========] 1319 tests from 200 test cases ran. (69251 ms total)
[  PASSED  ] 1319 tests.

In the newest version, all the unit tests can pass on CentOS and Ubuntu 14.04.

**Comment by hshen14** [comment]
The issue was resolved.
