### ISSUE TITLE
an error occured when I install caffe in my Ubuntu16.04 virtual machine which was installed in VMware Workstation 14.1.4

### ISSUE THREAD

**Issue by hzr1140521792** [intel/caffe#169]
`awk: line 1: syntax error at or near =
make: command：命令未找到
disabling weight grad compression if USE_MLSL is not 1
`

**Comment by ftian1** [comment]
details?

**Comment by ftian1** [comment]
The first line message is our script issue and will be fixed at next release.
The next line is a just message. it's not an error.
