### ISSUE TITLE
intelcaffe occupy the multi-thread resource and can not be used in follow process

### ISSUE THREAD

**Issue by cloudswenable** [intel/caffe#17]
Hi guys,
    Our usage is use caffe to extract features and then use multi-thread to do searching. We found one issue that when extracted features by caffe and we can not start up multi-threads to do the searching and only one thread can be used.  BTW , we use pthread to start multi-threads.

**Comment by pnoga** [comment]
Could you describe more your configuration and problem? Could you provide us logs from execution?

**Comment by pnoga** [comment]
Closing. If this problem is still valid please open new issue and atach more logs and your setup configuration.
