### ISSUE TITLE
An error occured when I excuted make all -j command to intall caffe

### ISSUE THREAD

**Issue by hzr1140521792** [intel/caffe#170]
`src/caffe/util/math_functions.cpp:39:31: fatal error: mkl_vml_functions.h: No such file or directory`

**Comment by chuanqi129** [comment]
Can you reproduce this error? If yes, please add more information, such as OS, CPU...

**Comment by hshen14** [comment]
The issue looks like you missed the mklml libraries. Please check whether the network is good to download via ./external/scripts/prepare_mkl.sh.
