### ISSUE TITLE
Not an issue connected to the code in this repository

### ISSUE THREAD

**Issue by paalped** [intel/caffe#171]
Hi,
I am just wondering if any of you clever intel people have the ability to implement MS TransmitFile zero-copy API to python on windows for transmitting files? 
Link to MS Api: https://msdn.microsoft.com/en-us/library/windows/desktop/ms740565(v=vs.85).aspx
Link to zero-copy wiki: https://en.wikipedia.org/wiki/Zero-copy
Link to bug issue: https://bugs.python.org/issue21721

I'm sorry if this is unapproriate to post here, but I don't know how to contact about this matter, and I thought that you guys would also benefit from fixing this issue, if you guys are running tests on windows.

**Comment by hshen14** [comment]
Please raise the question to the appropriate place, thanks.
