### ISSUE TITLE
Build in OSX error

### ISSUE THREAD

**Issue by tulanglaoli** [intel/caffe#172]
hello，
I build in my mac pro,at last ,I got the following error:
```
[  5%] Building CXX object src/caffe/CMakeFiles/caffe.dir/internal_thread.cpp.o
/Users/licheng/GitProject/caffe/src/caffe/internal_thread.cpp:125:5: error:
      unknown type name 'cpu_set_t'
    cpu_set_t set;
    ^
/Users/licheng/GitProject/caffe/src/caffe/internal_thread.cpp:129:51: error:
      use of undeclared identifier 'cpu_set_t'
    int s = pthread_setaffinity_np(thread, sizeof(cpu_set_t), &set);
                                                  ^
/Users/licheng/GitProject/caffe/src/caffe/internal_thread.cpp:133:21: error:
      use of undeclared identifier 'CPU_SETSIZE'
    for (int j=0; j<CPU_SETSIZE; j++) {
                    ^
3 errors generated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/internal_thread.cpp.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2
```

I've no idea how to solve it. It looks I miss something to install.
 my computer is :
macOs 10.13.2
2.9GHz intel Core i7

**Comment by ens-lg4** [comment]
Exactly the same problem here (on macOS 10.12.6)
Any progress on this issue?

Cheers!

**Comment by fzou1** [comment]
Sorry for late reply. Could you comment out SetThreadAffinity function in src/caffe/internal_thread.cpp before build? We may disable these lines of code on Mac OS next release.

**Comment by ens-lg4** [comment]
Thanks, your advice helped at least with this particular issue.

Still about 6-7 places to patch in order to run things on a Mac.

**Comment by hshen14** [comment]
Please raise the PR if needed. Thanks.

**Comment by AndsonYe** [comment]
I came into an error on MacOs

LD -o .build_release/lib/libcaffe.so.1.1.6
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How to fix this one?
