### ISSUE TITLE
Intel Caffe AlexNet - Run Time Variation On Intel Xeon Phi

### ISSUE THREAD

**Issue by PatilChetan** [intel/caffe#175]
Hi All,

I am profiling Intel Caffe which runs AlexNet. The number of iteration is 1000 and batch size is 256. I make use of OpenMP to distribute 128 threads. I explicitly provide thread mapping list which replicates scatter i.e. allocate threads to 0-63 and then 64-127.

However, I observe different run time (huge variation) between two runs of the above simulation. In first run, I get run time as 55.8 mins and second run I get run time as 42.5 mins. I was expecting difference between two runs of same Intel Caffe workload to be within 1%, but here I observe run time different of more than 23%. After first run I flush the DRAM and ensure that the new run has all 116 GB available to it (100GB DDR4 + 16GB MCDRAM in All-2-All Flat Mode).

Is this due to any specific learning parameters, random seeding in the network that changes for every new run? How I can ensure the variation among two runs for same network don't change?

Can anyone please suggest possible reason for this?

Thanks,
Chetan Arvind Patil

**Comment by fzou1** [comment]
Did you use scripts/run_intelcaffe.sh to run AlexNet? It should use correct numactl command running on Xeon Phi. Please have a try.
