### ISSUE TITLE
Upstream to BVLC/Caffe

### ISSUE THREAD

**Issue by dashesy** [intel/caffe#176]
It looks like intel/caffe is caffe with a new mkl-dnn engine
Is there any plan to upstream the changes here to BVLC/Caffe? What are the problems (licensing, ...)?

**Comment by hshen14** [comment]
BVLC Caffe actually had the branch linking to Intel Caffe: https://github.com/BVLC/caffe/tree/intel

**Comment by dashesy** [comment]
@hshen14 yes but it is not same as upstreaming (i.e. merging code improvements back to upstream). Now I think caffe development does not encourage merging back, everyone has a fork of caffe!

**Comment by jgong5** [comment]
@dashesy we have no plan to merge the changes back to BVLC Caffe master branch but we do keep IntelCaffe compatible with BVLC Caffe for IA. If you found anything not compatible, it is a bug and we would love to fix it.
