### ISSUE TITLE
mkldnn error for SSD with large batch size(2048)

### ISSUE THREAD

**Issue by kaiseu** [intel/caffe#181]
CPU mode with server memory 256GB, batch size 2048.

caffe test --detection --model /mnt/disk1/SSD_Predict/models/ssd/caffe/VGGNet/VOC0712/SSD_300x300/test.prototxt --weights /mnt/disk1/SSD_Predict/models/ssd/caffe/VGGNet/VOC0712/SSD_300x300/VGG_VOC0712_SSD_300x300_iter_120000.caffemodel --iterations=2

terminate called after throwing an instance of 'mkldnn::error'
  what():  std::exception
*** Aborted at 1518138760 (unix time) try "date -d @1518138760" if you are using GNU date ***
PC: @     0x7f628839e1f7 __GI_raise
*** SIGABRT (@0x3996f) received by PID 235887 (TID 0x7f6295c84a80) from PID 235887; stack trace: ***
    @     0x7f628839e270 (unknown)
    @     0x7f628839e1f7 __GI_raise
    @     0x7f628839f8e8 __GI_abort
    @     0x7f6289048ac5 (unknown)
    @     0x7f6289046a36 (unknown)
    @     0x7f6289046a63 (unknown)
    @     0x7f6289046c83 (unknown)
    @     0x7f628b8df282 mkldnn::error::wrap_c_api()
    @     0x7f628b8e0e1e mkldnn::memory::memory()
    @     0x7f628bb31ebc caffe::MKLDNNMemoryDescriptorBase<>::allocate()
    @     0x7f628bb3b3e8 caffe::MKLDNNMemoryDescriptor<>::create_reorder_to_prv()
    @     0x7f628bb30e62 caffe::MKLDNNMemoryDescriptor<>::get_blob_prv_primitive()
    @     0x7f628bb322d6 caffe::MKLDNNMemoryDescriptor<>::create_input()
    @     0x7f628bb32433 caffe::MKLDNNMemoryDescriptor<>::create_input()
    @     0x7f628b9903d6 caffe::MKLDNNConvolutionLayer<>::InitConvolutionFwd()
    @     0x7f628b9931be caffe::MKLDNNConvolutionLayer<>::Forward_cpu()
    @     0x7f628b88af72 caffe::Net<>::ForwardFromTo()
    @     0x7f628b88b1a7 caffe::Net<>::Forward()
    @     0x55fc1090dbe0 test_detection()
    @     0x55fc10910615 test()
    @     0x55fc1090c50c main
    @     0x7f628838ac05 __libc_start_main
    @     0x55fc1090d29d (unknown)

**Comment by ftian1** [comment]
memory allocation fails.

**Comment by ftian1** [comment]
close due to no reponse.
