### ISSUE TITLE
Is there any plan to add the depthwise conv for mobilenet and merged conv_relu layer?

### ISSUE THREAD

**Issue by fei1107** [intel/caffe#187]

**Comment by jgong5** [comment]
The optimized depth-wise convolution will be available soon.
The convolution-and-ReLU fusion has already been supported.

**Comment by fei1107** [comment]
@jgong5 Thanks for your reply! But I only find the merged relu in mkldnn library , and cannot find any layer definition in Caffe about the convolution_and _relu layer, could you tell me how to use that?

**Comment by jgong5** [comment]
@fei1107 IntelCaffe just remove or skip the ReLU computation and set a flag in convolution layer so that convolution knows it should do conv+ReLU at the same time.

**Comment by fei1107** [comment]
@jgong5 I find this in net.cpp:
  // Optimization rule 2:
    // - If we are having engine MKLDNN and ReLU layer within a model
    // and input bottom comes from  Convolution of engine MKLDNN
    // then we can remove ReLU layer
    // and rename Convolution top blob after deleted ReLU's top
    // Note: Currently merging of convolution and relu layers is feasible
    // If current layer is Convolution of MKLDNN engine..

is there any flag I have to set or it will be done automatically? and is there any time schedule about mobilenet? Many thanks!

**Comment by hshen14** [comment]
It is done automatically. We will release it by next release in 1 ~ 2 weeks.

**Comment by xizi** [comment]
@jgong5 hi, has the optimized depth-wise convolution available?

**Comment by jgong5** [comment]
@xizi Yes.

**Comment by xizi** [comment]
@jgong5 what the name of depth-wise convolution layer?

**Comment by xizi** [comment]
@jgong5 can i test a model which is trained by original caffe in intel-caffe?

**Comment by jgong5** [comment]
@xizi It is just the mkldnn conv layer, not special *layer* for depth-wise conv. MKL-DNN would dispatch to the right algorithm per conv shape.

**Comment by jgong5** [comment]
> @jgong5 can i test a model which is trained by original caffe in intel-caffe?

Yes.

**Comment by xizi** [comment]
@jgong5 could you give me you wechat number，i have some problem in using intel-caffe？ my wechat is xizi_fish

**Comment by xizi** [comment]
@jgong5 When i test mobilenet which is trained by original caffe, it reports error as follow:
F0415 21:10:09.769443 573441 net.cpp:2030] Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv2_1/dw
*** Check failure stack trace: ***
    @     0x7f6885ad5c0d  google::LogMessage::Fail()
    @     0x7f6885ad7a7f  google::LogMessage::SendToLog()
    @     0x7f6885ad57a3  google::LogMessage::Flush()
    @     0x7f6885ad839e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f6885fe0415  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x7f6885fe0574  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x7f688f8c0de0  Classifier::Classifier()
    @     0x7f688f8bddcf  main
    @     0x7f6882ea8c05  __libc_start_main
    @     0x7f688f8be5d7  (unknown)
and the deploy.prototxt is 
layer {
  name: "conv2_1/dw"
  type: "Convolution"
  bottom: "conv1"
  top: "conv2_1/dw"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  convolution_param {
    num_output: 32
    bias_term: false
    pad: 1
    kernel_size: 3
    group: 32
    stride: 1
    weight_filler {
      type: "msra"
    }
  }
}
can you help me figure out?

**Comment by xizi** [comment]
@jgong5 Hi, do you have some idea about above error?

**Comment by ftian1** [comment]
could you share me the weight file? I need reproduce it at my side at first

**Comment by xizi** [comment]
@ftian1 i can not share the weight file, but i print the size of target_blobs and source_layer, the original caffe print as follow:
target_blobs.size: 1 source_layer.size: 1 conv1
target_blobs.size: 3 source_layer.size: 3 conv1/bn
target_blobs.size: 2 source_layer.size: 2 conv1/scale
target_blobs.size: 0 source_layer.size: 0 relu1
target_blobs.size: 1 source_layer.size: 1 conv2_1/dw
target_blobs.size: 3 source_layer.size: 3 conv2_1/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv2_1/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu2_1/dw
target_blobs.size: 1 source_layer.size: 1 conv2_1/sep
target_blobs.size: 3 source_layer.size: 3 conv2_1/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv2_1/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu2_1/sep
target_blobs.size: 1 source_layer.size: 1 conv2_2/dw
target_blobs.size: 3 source_layer.size: 3 conv2_2/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv2_2/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu2_2/dw
target_blobs.size: 1 source_layer.size: 1 conv2_2/sep
target_blobs.size: 3 source_layer.size: 3 conv2_2/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv2_2/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu2_2/sep
target_blobs.size: 1 source_layer.size: 1 conv3_1/dw
target_blobs.size: 3 source_layer.size: 3 conv3_1/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv3_1/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu3_1/dw
target_blobs.size: 1 source_layer.size: 1 conv3_1/sep
target_blobs.size: 3 source_layer.size: 3 conv3_1/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv3_1/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu3_1/sep
target_blobs.size: 1 source_layer.size: 1 conv3_2/dw
target_blobs.size: 3 source_layer.size: 3 conv3_2/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv3_2/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu3_2/dw
target_blobs.size: 1 source_layer.size: 1 conv3_2/sep
target_blobs.size: 3 source_layer.size: 3 conv3_2/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv3_2/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu3_2/sep
target_blobs.size: 1 source_layer.size: 1 conv4_1/dw
target_blobs.size: 3 source_layer.size: 3 conv4_1/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv4_1/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu4_1/dw
target_blobs.size: 1 source_layer.size: 1 conv4_1/sep
target_blobs.size: 3 source_layer.size: 3 conv4_1/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv4_1/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu4_1/sep
target_blobs.size: 1 source_layer.size: 1 conv4_2/dw
target_blobs.size: 3 source_layer.size: 3 conv4_2/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv4_2/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu4_2/dw
target_blobs.size: 1 source_layer.size: 1 conv4_2/sep
target_blobs.size: 3 source_layer.size: 3 conv4_2/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv4_2/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu4_2/sep
target_blobs.size: 1 source_layer.size: 1 conv5_1/dw
target_blobs.size: 3 source_layer.size: 3 conv5_1/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv5_1/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu5_1/dw
target_blobs.size: 1 source_layer.size: 1 conv5_1/sep
target_blobs.size: 3 source_layer.size: 3 conv5_1/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv5_1/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu5_1/sep
target_blobs.size: 1 source_layer.size: 1 conv5_2/dw
target_blobs.size: 3 source_layer.size: 3 conv5_2/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv5_2/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu5_2/dw
target_blobs.size: 1 source_layer.size: 1 conv5_2/sep
target_blobs.size: 3 source_layer.size: 3 conv5_2/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv5_2/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu5_2/sep
target_blobs.size: 1 source_layer.size: 1 conv5_3/dw
target_blobs.size: 3 source_layer.size: 3 conv5_3/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv5_3/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu5_3/dw
target_blobs.size: 1 source_layer.size: 1 conv5_3/sep
target_blobs.size: 3 source_layer.size: 3 conv5_3/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv5_3/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu5_3/sep
target_blobs.size: 1 source_layer.size: 1 conv5_4/dw
target_blobs.size: 3 source_layer.size: 3 conv5_4/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv5_4/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu5_4/dw
target_blobs.size: 1 source_layer.size: 1 conv5_4/sep
target_blobs.size: 3 source_layer.size: 3 conv5_4/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv5_4/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu5_4/sep
target_blobs.size: 1 source_layer.size: 1 conv5_5/dw
target_blobs.size: 3 source_layer.size: 3 conv5_5/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv5_5/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu5_5/dw
target_blobs.size: 1 source_layer.size: 1 conv5_5/sep
target_blobs.size: 3 source_layer.size: 3 conv5_5/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv5_5/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu5_5/sep
target_blobs.size: 1 source_layer.size: 1 conv5_6/dw
target_blobs.size: 3 source_layer.size: 3 conv5_6/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv5_6/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu5_6/dw
target_blobs.size: 1 source_layer.size: 1 conv5_6/sep
target_blobs.size: 3 source_layer.size: 3 conv5_6/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv5_6/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu5_6/sep
target_blobs.size: 1 source_layer.size: 1 conv6/dw
target_blobs.size: 3 source_layer.size: 3 conv6/dw/bn
target_blobs.size: 2 source_layer.size: 2 conv6/dw/scale
target_blobs.size: 0 source_layer.size: 0 relu6/dw
target_blobs.size: 1 source_layer.size: 1 conv6/sep
target_blobs.size: 3 source_layer.size: 3 conv6/sep/bn
target_blobs.size: 2 source_layer.size: 2 conv6/sep/scale
target_blobs.size: 0 source_layer.size: 0 relu6/sep
target_blobs.size: 0 source_layer.size: 0 pool6
but the intel caffe print:
target_blobs.size: 2 source_layer.size: 2 conv1
target_blobs.size: 2 source_layer.size: 1 conv2_1/dw
Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv2_1/dw

does the intel caffe ignore bn or someting?

**Comment by xizi** [comment]
target_blobs.size: 2 source_layer.size: 2 conv1
target_blobs.size: 2 source_layer.size: 1 conv2_1/dw
target_blobs.size: 2 source_layer.size: 2 conv2_1/sep
target_blobs.size: 2 source_layer.size: 1 conv2_2/dw
target_blobs.size: 2 source_layer.size: 2 conv2_2/sep
target_blobs.size: 2 source_layer.size: 1 conv3_1/dw
target_blobs.size: 2 source_layer.size: 2 conv3_1/sep
target_blobs.size: 2 source_layer.size: 1 conv3_2/dw
target_blobs.size: 2 source_layer.size: 2 conv3_2/sep
target_blobs.size: 2 source_layer.size: 1 conv4_1/dw
target_blobs.size: 2 source_layer.size: 2 conv4_1/sep
target_blobs.size: 2 source_layer.size: 1 conv4_2/dw
target_blobs.size: 2 source_layer.size: 2 conv4_2/sep
target_blobs.size: 2 source_layer.size: 1 conv5_1/dw
target_blobs.size: 2 source_layer.size: 2 conv5_1/sep
target_blobs.size: 2 source_layer.size: 1 conv5_2/dw
target_blobs.size: 2 source_layer.size: 2 conv5_2/sep
target_blobs.size: 2 source_layer.size: 1 conv5_3/dw
target_blobs.size: 2 source_layer.size: 2 conv5_3/sep
target_blobs.size: 2 source_layer.size: 1 conv5_4/dw
target_blobs.size: 2 source_layer.size: 2 conv5_4/sep
target_blobs.size: 2 source_layer.size: 1 conv5_5/dw
target_blobs.size: 2 source_layer.size: 2 conv5_5/sep
target_blobs.size: 2 source_layer.size: 1 conv5_6/dw
target_blobs.size: 2 source_layer.size: 2 conv5_6/sep
target_blobs.size: 2 source_layer.size: 1 conv6/dw
target_blobs.size: 2 source_layer.size: 2 conv6/sep
target_blobs.size: 0 source_layer.size: 0 pool6

**Comment by ftian1** [comment]
pls show me the entire mobilenet prototxt you used.

**Comment by xizi** [comment]
@ftian1 Hi, i have send a mail to you with the prototxt.

**Comment by ftian1** [comment]
could you let me know if below cmd works or not at your side?

./build/tools/caffe time -model mb.pt --forward_only --phase TEST --iterations 2

**Comment by xizi** [comment]
./build/examples/cpp_classification/classification.bin deploy.prototxt model.caffemodel mean.binaryproto label.txt MKLDNN

**Comment by ftian1** [comment]
@xizi I am asking if "./build/tools/caffe time -model deploy.prototxt --forward_only --phase TEST --iterations 2" rather than the cmd you used works at your side.

**Comment by xizi** [comment]
@ftian1 it works.
