### ISSUE TITLE
I can not use mkldnn, and I can not find the reason.

### ISSUE THREAD

**Issue by wuzhijiexia** [intel/caffe#19]
I download mkldnn from the address(https://github.com/01org/mkl-dnn), meanwhile compile and install successfully.
Then, I set env var MKLDNNROOT as /usr/local.
When I begin to compile caffe, the problem is below:
![image 3](https://cloud.githubusercontent.com/assets/19603119/20296232/9661d83e-ab44-11e6-9567-72de5a148449.png)

**Comment by benerit** [comment]
What compiler type / version did you used?

**Comment by wuzhijiexia** [comment]
mkldnn === GCC 4.8.5
caffe === ICC 17.0.1

**Comment by tpatejko** [comment]
Thank you for reporting the issue. We will be looking at it.

In the meantime, could you build both intelcaffe and mkl-dnn with GCC? We checked this configuration and it should work.

**Comment by wuzhijiexia** [comment]
I had tried it, building both intelcaffe and mkl-dnn with GCC( or ICC ). But the errors still exist. 
Example:
.../mkldnn_memory.cpp:351:76: error: 'set_extprv_memory_pd' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantion [-fpermissive]

**Comment by pnoga** [comment]
please retest with new release

**Comment by HAIDJ** [comment]
@pnoga 
Dear pnoga,

I have found the same problem above from the latest [caffe](https://github.com/intel/caffe) with the latest [MKL-DNN](https://github.com/01org/mkl-dnn).

I used xeon-phi 7250 CPU

please below additional information
gcc version: 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
icc version: 17.0.1 (gcc version 4.8.5 compatibility)
build command: CC=icc CXX=icpc make all -j64

Do you have any suggetion?

Thank you,
Daejin Jung
```
src/caffe/mkldnn_memory.cpp(242): error: no suitable constructor exists to convert from "long" to "boost::shared_ptr<caffe::PrvMemDescr>"blob->set_prv_diff_descriptor(NULL);
                                                                                                                      ^
detected during instantiation of "boost::shared_ptr<mkldnn::primitive> caffe::MKLDNNMemoryDescriptor<Dtype, is_diff>::get_blob_prv_primitive(caffe::Blob<Dtype> *, bool, bool, caffe::MKLDNNMemoryDescriptor<Dtype, is_diff> *) [with Dtype=double, is_diff=true]" at line 394
```
```
src/caffe/mkldnn_memory.cpp(247): error: no suitable constructor exists to convert from "long" to "boost::shared_ptr<caffe::PrvMemDescr>" blob->set_prv_data_descriptor(NULL);
                                                                                                                         ^
detected during instantiation of "boost::shared_ptr<mkldnn::primitive> caffe::MKLDNNMemoryDescriptor<Dtype, is_diff>::get_blob_prv_primitive(caffe::Blob<Dtype> *, bool, bool, caffe::MKLDNNMemoryDescriptor<Dtype, is_diff> *) [with Dtype=double, is_diff=true]" at line 394
```
```
src/caffe/layers/mkldnn_inner_product_layer.cpp(70): error: no instance of constructor "boost::shared_ptr<T>::shared_ptr [with T=caffe::MKLDNNDiff<double>]" matches the argument list
            argument types are: (long)
              bwdw_weights_diff(NULL),
                               ^
```
