### ISSUE TITLE
unable to build caffe using icc/icpc when protobuf==3.5.2 installed

### ISSUE THREAD

**Issue by rohit-jamuar** [intel/caffe#190]
```
caffe version: 1.1.0
icpc (ICC) 16.0.3 20160415
icc (ICC) 16.0.3 20160415
```

When trying to build caffe using a pre-installed protobuf (i.e. version 3.5.2) with icpc, the build fails with :
```
In file included from .build_release/src/caffe/proto/caffe.pb.h(25),
         from .build_release/src/caffe/proto/caffe.pb.cc(4):
         /workdir/include/google/protobuf/generated_message_table_driven.h(188): error: static assertion failed with ""
         static_assert(std::is_pod<AuxillaryParseTableField>::value, "");
```

The same can be built with g++. Any idea how to fix this?

Thanks,
Rohit

**Comment by fzou1** [comment]
Please check line 25 in caffe.pb.h. I believe caffe may not be compatible with this protobuf. could you try protobuf with version 2.5.0?

**Comment by rohit-jamuar** [comment]
The problem is that I have to build other modules that have a hard-requirement on the version of protobuf - it would not be possible for me to use an older version of protobuf. The problem doesn't come up while building with g++. Any idea as to why protoc is generating code that's causing compiler issues when compilation is done using icpc? Should the proto files be altered so that generated code can be compiled using icpc?

**Comment by rohit-jamuar** [comment]
@fzou1 It would also be helpful in understanding the performance implication of building with g++, as opposed to icpc. Could you please point me to performance-data comparing effects of using icpc over g++, for building caffe?

**Comment by chuanqi129** [comment]
@rohit-jamuar Hi, could you please give more information? Such as `protoc --version` and the method of build caffe, make or camke? In my test, I can build successfully. My `protoc --version` is `3.5.1` but I compiled and installed it by source code v3.5.2. So I'm not sure if it's the same version as your protoc. In addition, I lists my information as below.

> caffe version: 1.1.0
> icpc (ICC) 18.0.1 20171018
> icc (ICC) 18.0.1 20171018
> protoc --version: 3.5.1 (compiled and installed by source code v3.5.2, I don't know why)
> build method: cmake

**Comment by hshen14** [comment]
Close it due to no activities recently. Please feel free to reopen it.

**Comment by kaurrachneet6** [comment]
Did you solve this error. I have same.
