### ISSUE TITLE
multiple input size error in mkl2017

### ISSUE THREAD

**Issue by manlinting** [intel/caffe#193]
I'm working on a super-resolution project using intel caffe in the ?test phase. When I use the CAFFE engine it's OK, but when I switch to MKL2017, only the first picture is correct, and the other pictures have problems. Does MKL2017 not support inputting multiple input size of resolution images? Can you tell us how to change it?

**Comment by ftian1** [comment]
mkl2017 is deprecated and not all MKL2017 layers handle different image shape. Pls use default engine, that's MKLDNN engine for you case.

**Comment by manlinting** [comment]
Mkldnn does not seem to support a layer connected to multiple layers at the same time

**Comment by hshen14** [comment]
would you please share the model prototxt?

**Comment by ftian1** [comment]
@manlinting what do you mean MKLDNN doesn't support a layer connecting to multiple layers? we will automatically add split layers if the output blob is consumed by multiple consumers/layers. it has nothing to do with the engine used.
