### ISSUE TITLE
when i user the caffe/tools/extra/plot_training_log.py.example?some problem..

### ISSUE THREAD

**Issue by poppingcode** [intel/caffe#198]
after training,product a file named a.log
i want show the test accuracy vs Iters
so i run ：python plot_training_log.py 0 a0.png a.log
it hint that 
File " plot_training_log.py" ,line 82 ,in load_data
     with open(data_file , 'r') as f:
IOError: [Errno 2 ] No such file or directory : a.log.test

thanks

**Comment by hshen14** [comment]
It is fixed internally and will be upstreamed soon.
