### ISSUE TITLE
why not support this ? version?

### ISSUE THREAD

**Issue by githublet** [intel/caffe#200]
https://github.com/golunovas/mtcnn-cpp 
Segmentation fault.

**Comment by fzou1** [comment]
Could you provide trace or log? Thanks.

**Comment by githublet** [comment]
}
}
layer {
  name: "prob1"
  type: "Softmax"
  bottom: "conv4-1"
  top: "prob1"
}
I0427 21:14:19.505735 28006 layer_factory.hpp:114] Creating layer input
I0427 21:14:19.505789 28006 net.cpp:261] Creating Layer input
I0427 21:14:19.505820 28006 net.cpp:1472] input -> data
I0427 21:14:19.505933 28006 net.cpp:330] Setting up input
Segmentation fault (core dumped)


something look like this~

**Comment by githublet** [comment]
TARGET = facetector
CC = gcc
CP = g++
# 主目标文件
MAIN_OBJS = face_detector.o main.o

ALL_OBJS = $(MAIN_OBJS)

CAFFE_INC= -I/home/zt/caffe-master/build/install/include
CAFFE_LIB= -llmdb -lcaffe -L/home/zt/caffe-master/build/install/lib

#OPENCV
OPENCV_INC = -I/usr/local/cuda-8.0/include
OPENCV_LIB = `pkg-config --cflags --libs opencv`

#boost
BOOST_LIB = -lboost_python -lboost_system -lboost_thread -lboost_filesystem

CPFLAGS = -D_REENTRANT -fPIC -std=c++11 -Wall -fpermissive -fmessage-length=0
CPFLAGS		+= -g
CPFLAGS += $(OPENCV_INC) $(CAFFE_INC)

OTHER_LIB = -lglog -luuid -lpthread -ldl -lz

LFLAGS = -L/usr/local/lib64 -L/usr/local/lib -L/usr/lib -ftemplate-depth-128  -D_REENTRANT -fPIC 
LFLAGS += -Wl,-dn -Wl,-dy $(OPENCV_LIB)  $(BOOST_LIB) $(CAFFE_LIB)  $(OTHER_LIB)

$(TARGET) : $(ALL_OBJS)
	$(CP)  -o $(TARGET) $(ALL_OBJS) $(LFLAGS)
	
$(MAIN_OBJS): %.o: %.cpp
	$(CP) -c $(CPFLAGS) $< -o $@
	
.PHONY : clean
clean :
	rm $(TARGET) $(ALL_OBJS)

My makefile for mtcnn~

**Comment by githublet** [comment]
blob.hpp : 94
shape_.size() wrong

**Comment by ftian1** [comment]
why you use this code rather than original author's? nobody ensure the code's quality you used. pls do the debug by yourself.
