### ISSUE TITLE
identifier "regexec" is undefined

### ISSUE THREAD

**Issue by DavidBrayford** [intel/caffe#208]
I am getting several compilation errors related to regex (see below) with intel icpc version 17.0.6.256.

I executed the command scripts/prepare_env.sh which downloaded and built boost 1.64.0

Building CXX object src/gmock/CMakeFiles/gmock.dir/__/gtest/src/gtest-all.cpp.o
cd /home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/build/src/gmock && /lrz/sys/intel/studio2017_u6/compilers_and_libraries_2017.6.256/linux/bin/intel64/icpc   -DCAFFE_VERSION=1.1.0 -DCPU_ONLY -DDISABLE_MKLDNN_DOWNLOAD=0 -DFOUNDED_MLSL_ROOT=/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/./external/mlsl/l_mlsl_2018.0.003/ -DFW_OVERLAP_OPT -DGTEST_USE_OWN_TR1_TUPLE -DUSE_LEVELDB -DUSE_LMDB -DUSE_MKL -DUSE_MLSL=1 -DUSE_OPENCV -I/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gmock/include -I/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gtest/include -isystem /home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/boost_1_64_0/install/include -isystem /home/hpc/pr28fa/di72giz/CAFFE_INTEL/GLOG/glog/build/release_ICC/include -isystem /home/hpc/pr28fa/di72giz/CAFFE_INTEL/GFLAGS/gflags/build/release_ICC/include -isystem /home/hpc/pr28fa/di72giz/CAFFE_INTEL/protobuf-3.1.0/build/release_icc/include -I/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/build/include -isystem /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/include -isystem /home/hpc/pr28fa/di72giz/CAFFE_INTEL/lmdb-mdb.master/libraries/liblmdb/include -isystem /home/hpc/pr28fa/di72giz/CAFFE_INTEL/leveldb-master/include -isystem /home/hpc/pr28fa/di72giz/CAFFE_INTEL/snappy-1.1.3/build/release/include -isystem /home/hpc/pr28fa/di72giz/Anaconda/anaconda3/include/opencv -isystem /home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/./external/mlsl/l_mlsl_2018.0.003/intel64/include -isystem /home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/external/ideep/ideep/dlcp/include -isystem /home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/./external/mkl/mklml_lnx_2018.0.1.20171227/include -I/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/external/mkldnn/install/include -I/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/include -I/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/build -I/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gmock -I/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gtest  -fpic -qopenmp -DENABLE_WEIGHT_GRAD_COMPRESSION -DMKL2017_SUPPORTED -DMKLDNN_SUPPORTED -std=c++11 -DUSE_MKLDNN_AS_DEFAULT_ENGINE -fstack-protector -wd2196 -DENABLE_SGD_FUSION -fPIC -fno-operator-names -Wformat -Wformat-security -Wall -std=c++11 -Werror -O3 -DNDEBUG -D_FORTIFY_SOURCE=2   -fpic -qopenmp -DENABLE_WEIGHT_GRAD_COMPRESSION -DMKL2017_SUPPORTED -DMKLDNN_SUPPORTED -std=c++11 -DUSE_MKLDNN_AS_DEFAULT_ENGINE -fstack-protector -wd2196 -DENABLE_SGD_FUSION -fPIC -fno-operator-names -Wformat -Wformat-security -Wall -std=c++11 -Werror  -DGTEST_HAS_PTHREAD=1   -o CMakeFiles/gmock.dir/__/gtest/src/gtest-all.cpp.o -c /home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gtest/src/gtest-all.cpp
In file included from /home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gtest/src/gtest-all.cpp(45):
/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gtest/src/gtest-port.cc(157): error: identifier "regexec" is undefined
    return regexec(&re.full_regex_, str, 1, &match, 0) == 0;
           ^

In file included from /home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gtest/src/gtest-all.cpp(45):
/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gtest/src/gtest-port.cc(166): error: identifier "regexec" is undefined
    return regexec(&re.partial_regex_, str, 1, &match, 0) == 0;
           ^

In file included from /home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gtest/src/gtest-all.cpp(45):
/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gtest/src/gtest-port.cc(179): error: identifier "regcomp" is undefined
    is_valid_ = regcomp(&full_regex_, full_pattern, REG_EXTENDED) == 0;
                ^

compilation aborted for /home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/src/gtest/src/gtest-all.cpp (code 2)
src/gmock/CMakeFiles/gmock.dir/build.make:65: recipe for target 'src/gmock/CMakeFiles/gmock.dir/__/gtest/src/gtest-all.cpp.o' failed
make[2]: *** [src/gmock/CMakeFiles/gmock.dir/__/gtest/src/gtest-all.cpp.o] Error 2
make[2]: Leaving directory '/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/build'
CMakeFiles/Makefile2:260: recipe for target 'src/gmock/CMakeFiles/gmock.dir/all' failed
make[1]: *** [src/gmock/CMakeFiles/gmock.dir/all] Error 2
make[1]: Leaving directory '/home/hpc/pr28fa/di72giz/CAFFE_INTEL/caffe/build'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2

David

**Comment by hshen14** [comment]
Did you follow the build instruction on Intel Caffe?

**Comment by DavidBrayford** [comment]
The problem was that the cmake script was taking regex.h from python3 (the regex frontend functions are disabled (#define __REG_NOFRONT) ). To resolve this I forced the script to use /usr/include/regex.x

**Comment by hshen14** [comment]
Make sense, thanks for your finding and solution.
