### ISSUE TITLE
Fail to make by shared library of boost

### ISSUE THREAD

**Issue by lz1313** [intel/caffe#21]
/usr/bin/ld: .build_release/src/caffe/multinode/SynchronousNode.o: relocation R_X86_64_TPOFF32 against `boost::asio::detail::keyword_tss_ptr::context>::value_' can not be used when making a shared object; recompile with -fPIC
.build_release/src/caffe/multinode/SynchronousNode.o: could not read symbols: Bad value

Updated, reset, re-compiled, but still same story with one of closed issues

**Comment by apwojcik** [comment]
It looks like you are trying to link statically boost to libcaffe, and the boost static library wasn't compiled with -fPIC. Try to check [relocations](http://stackoverflow.com/questions/1340402/how-can-i-tell-with-something-like-objdump-if-an-object-file-has-been-built-wi) for each file in the static library then you'll be sure (empty set should be returned). It seams to me the static library you use is not position-independent and cannot be used to generate shared object i.e. libcaffe.so. You need version of boost compiled with -fPIC and you should use it instead.

**Comment by lz1313** [comment]
I am using CentOS 6, and GCC is only 4.4.7, so I upgrade it using an updated GCC, this issue is gone.
I will close this issue.
