### ISSUE TITLE
error: ‘accumulate’ is not a member of ‘std’, when building with CAFFE_PER_LAYER_TIMINGS=1

### ISSUE THREAD

**Issue by reazulhoque** [intel/caffe#217]
Compiling with GCC 7.2, the problem seems to arise because of a missing header file in the file Caffe_Root/src/caffe/net.cpp.

Possible solution: add "#include \<numeric\>" in Caffe_Root/src/caffe/net.cpp

**Comment by hshen14** [comment]
Will be fixed internally.

**Comment by ftian1** [comment]
will be released in next release
