### ISSUE TITLE
How the number of omp_threads are determined in a multinode run

### ISSUE THREAD

**Issue by reazulhoque** [intel/caffe#218]
I am trying to train GoogLeNet in multinode environment. I am using a cluster where the head node and the compute nodes are different. In the following code:

https://github.com/intel/caffe/blob/a3d5b022fe026e9092fc7abc7654b1162ab9940d/scripts/set_env.sh#L179

lscpu is done on headnode, while it should be done on compute node. What am I missing?

**Comment by hshen14** [comment]
Physical cores.

**Comment by ChongyuIntel** [comment]
•	Current implementation uses OpenMP threads. By default the number of OpenMP threads is set to the number of CPU cores. Each one thread is bound to a single core to achieve best performance results. It is however possible to use your own configuration by providing right one through OpenMP environmental variables like KMP_AFFINITY, OMP_NUM_THREADS or GOMP_CPU_AFFINITY. 
o	For Intel Xeon Knights Mill and Knights Lading multi-node test we recommend to use OMP_NUM_THREADS = numer_of_corres-4. 
o	For Intel Xeon Scalable processors (Skylake) product we recommend to use OMP_NUM_THREADS = numer_of_corres-2.
