### ISSUE TITLE
What is differencies of two engines, CAFFE and MKL2017?

### ISSUE THREAD

**Issue by wuzhijiexia** [intel/caffe#22]
What is the engine?
What is differencies of two engines, CAFFE and MKL2017?

**Comment by heagoo** [comment]
My understanding:
The CAFFE engine uses the default implementation in bvlc caffe, with optimizations. For example, the convolution layer first call im2col, then call sgemm to calculate the convolution.
The MKL2017 engine uses MKL DNN primitivies in MKL.
In most times, MKL2017 should be faster, but with less support (I mean for some cases,  we cannot use MKL2017 engine, for example, it does not support dilated convolution)

**Comment by wuzhijiexia** [comment]
Thanks very much!
