### ISSUE TITLE
Aborted (core dumped) when run runtest or run mnist or anything else.

### ISSUE THREAD

**Issue by JoreyYan** [intel/caffe#231]
no matter what i do , it will always work like this, even when i import caffe in python and when i excute exit(), these things appear again, 

i finished make and make install 100%

i really hope some one give me help 

thank you very much

7f128ebd1000-7f128ebef000 r-xp 00000000 08:02 235678193                  /lib/x86_64-linux-gnu/libudev.so.1.6.4
7f128ebef000-7f128ebf0000 r--p 0001d000 08:02 235678193                  /lib/x86_64-linux-gnu/libudev.so.1.6.4
7f128ebf0000-7f128ebf1000 rw-p 0001e000 08:02 235678193                  /lib/x86_64-linux-gnu/libudev.so.1.6.4
7f128ebf1000-7f128ec29000 rw-p 00000000 00:00 0
7f128ec3d000-7f128ec3f000 rw-p 00000000 00:00 0
7f128ec3f000-7f128ec40000 r--p 00025000 08:02 217057414                  /lib/x86_64-linux-gnu/ld-2.23.so
7f128ec40000-7f128ec41000 rw-p 00026000 08:02 217057414                  /lib/x86_64-linux-gnu/ld-2.23.so
7f128ec41000-7f128ec42000 rw-p 00000000 00:00 0
7fff082bb000-7fff082db000 rwxp 00000000 00:00 0                          [stack]
7fff082db000-7fff082dc000 rw-p 00000000 00:00 0
7fff083c9000-7fff083cb000 r--p 00000000 00:00 0                          [vvar]
7fff083cb000-7fff083cd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
*** Aborted at 1534481958 (unix time) try "date -d @1534481958" if you are using GNU date ***
PC: @     0x7f127ec1a428 gsignal
*** SIGABRT (@0x15e73) received by PID 89715 (TID 0x7f128eb33b40) from PID 89715; stack trace: ***
    @     0x7f128d81d390 (unknown)
    @     0x7f127ec1a428 gsignal
    @     0x7f127ec1c02a abort
    @     0x7f127ec5c7ea (unknown)
    @     0x7f127ec6537a (unknown)
    @     0x7f127ec6953c cfree
    @     0x7f128d30d8af google::protobuf::internal::DestroyDefaultRepeatedFields()
    @     0x7f128d30cb3b google::protobuf::ShutdownProtobufLibrary()
    @     0x7f12644f93b9 (unknown)
    @     0x7f128ea2ade7 (unknown)
    @     0x7f127ec1eff8 (unknown)
    @     0x7f127ec1f045 exit
    @     0x7f127ec05837 __libc_start_main
    @     0x560bd5f55d39 _start
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by ftian1** [comment]
never met such case. it's more like protobuf issue.

another thing to highlight is pls ensure your python protobuf version is matching with your protobuf c version. otherwise you would meet problem later.
