### ISSUE TITLE
Can it improve inference speed on GPU?

### ISSUE THREAD

**Issue by le8888e** [intel/caffe#238]
Very impressive work. I am wondering whether it can improve inference speed on GPU. Thanks.

**Comment by MatthiasHertel80** [comment]
CMSIS-NN is very specifically targeted and optimized towards the Arm Cortex-M architecture and its SIMD instructions. No other platform would benefit from these optimizations.

**Comment by ftian1** [comment]
no. this repo is specific for caffe perf optimization on Xeon server.

you can refer to NvCaffe to see if it meets your requirement.
