### ISSUE TITLE
Maximum batch for GoogLenet

### ISSUE THREAD

**Issue by mycarrar** [intel/caffe#24]
Hey guys,
I hope this is the correct forum for tech support ;-)

I am trying to test the limits of an Intel Xeon Phi 7230 CPU running Intel Caffe built with MKL 17.0.098

I want to find the largest batch size possible. When I go beyond about 512 images per batch running the `caffe time` command using the mkl2017_googlenet_v1_knl/train_val.prototxt I get to the `"Performing Backward"` part and the job returns `killed`.

I am trying to diagnose whether this is an issue with the shared HPC system I am using (which uses PBS for scheduling) or whether this is the actual batch limit for this piece of hardware. The output `killed` is not very helpful and does not sound like it would be output from Caffe.

Please let me know if there is anything I can clarify. Thanks in advance for the help.

**Comment by pnoga** [comment]
For big batch you need more RAM memory - make sure during your proces that you have enough memory. 
Also if you wish to train network you need to be sure that you have specific hyper parameters that allow you to fully train network.
Currently we are recommending batchsize in range 32 - 128. Those are configurations that are under your validation - other are experimental and we plan to extend our support in the future.

**Comment by mycarrar** [comment]
Oh okay. I see one of the main differences in using the intel phi over a gpu is that you have more memory and thus can achieve a larger batch size. I'll keep experimenting.

While I have you here. Should hyperthreading speed up training time? I have found that if I use hyperthreading when I go from OMP_NUM_CORES=64 to OMP_NUM_CORES=256 Caffe actually slows down?

**Comment by pnoga** [comment]
Try to use HT and dont use OMP_NUM_CORES.
Solution for HT is being optimized (mostly for multinode). We are working to provide the best performance out of the box (without any additional commands or cores restrictions). Those changes should be released in one month.

**Comment by inJeans** [comment]
Hmmm. Okay. If I don't use OMP_NUM_THREADS then my job runs serially. Is HT another environment variable? There is a flag to enable hyperthreading when submitting the job but it doesn't let you specify the number of threads to use. I was following the guidelines here https://github.com/intel/caffe/wiki/Recommendations-to-achieve-best-performance that is why I was using OMP_NUM_THREADS

**Comment by pnoga** [comment]
HT is environment variable like configuration of MCDRAM.
We are focusing of research those variables and provide some best known configuration and develop new features that will use other configurations and give better performance - so our recommandation might change over time. 
There is no forum. We use this github for user support.

**Comment by jdukat** [comment]
Is there still anything to be discussed here? Can this issue be closed?

**Comment by inJeans** [comment]
Can I just confirm before you do. What do you think may be causing the issue of serial execution when I don't specify OMP_NUM_THREADS?

**Comment by pnoga** [comment]
Could you describe this issue? We are moving here from one topic to another. The best way will be to use separate threads for each issue.

**Comment by inJeans** [comment]
Of course. Above you suggested "dont use OMP_NUM_CORES." So I tried running without setting OMP_NUM_THREADS and as I said above, when I do so caffe seems to run serially? Even when I have set the HT option on.
