### ISSUE TITLE
Build the Cython modules error

### ISSUE THREAD

**Issue by nyanmn** [intel/caffe#246]
I am trying to make the faster rcnn work in my intel caffe.
I followed the instructions from the link <https://github.com/intel/caffe/tree/master/examples/faster-rcnn>.
I have errors in Build the Cython modules in second step.

The error is 

python setup.py build_ext --inplace
running build_ext
cythoning utils/mathutils.pyx to utils/mathutils.c

Error compiling Cython file:
------------------------------------------------------------
...
# Licensed under The MIT License [see LICENSE for details]
# Written by YAO Matrix
# --------------------------------------------------------

import numpy as np
cimport numpy as np
       ^
------------------------------------------------------------

utils/mathutils.pyx:9:8: 'numpy.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...

@cython.boundscheck(False)
@cython.wraparound(False)
def cpu_subtract(np.ndarray[np.float32_t, ndim=3] src, np.ndarray[np.float32_t, ndim=3] scalar):
                ^
------------------------------------------------------------

utils/mathutils.pyx:28:17: 'ndarray' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

@cython.boundscheck(False)
@cython.wraparound(False)
def cpu_subtract(np.ndarray[np.float32_t, ndim=3] src, np.ndarray[np.float32_t, ndim=3] scalar):
                                                      ^
------------------------------------------------------------

utils/mathutils.pyx:28:55: 'ndarray' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

    with nogil:
        for i in prange(rows, schedule = 'dynamic', num_threads = thread_num):
            for j in xrange(cols):
                for k in xrange(chs):
                    src[i, j, k] -= scalar[0, 0, k]
                      ^
------------------------------------------------------------

utils/mathutils.pyx:41:23: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

    with nogil:
        for i in prange(rows, schedule = 'dynamic', num_threads = thread_num):
            for j in xrange(cols):
                for k in xrange(chs):
                    src[i, j, k] -= scalar[0, 0, k]
                      ^
------------------------------------------------------------

utils/mathutils.pyx:41:23: Operation not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

    with nogil:
        for i in prange(rows, schedule = 'dynamic', num_threads = thread_num):
            for j in xrange(cols):
                for k in xrange(chs):
                    src[i, j, k] -= scalar[0, 0, k]
                      ^
------------------------------------------------------------

utils/mathutils.pyx:41:23: Operation not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

    with nogil:
        for i in prange(rows, schedule = 'dynamic', num_threads = thread_num):
            for j in xrange(cols):
                for k in xrange(chs):
                    src[i, j, k] -= scalar[0, 0, k]
                                         ^
------------------------------------------------------------

utils/mathutils.pyx:41:42: Constructing Python tuple not allowed without gil
building 'utils.cython_mathutils' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c utils/mathutils.c -o build/temp.linux-x86_64-2.7/utils/mathutils.o -O3 -Wno-cpp -Wno-unused-function
utils/mathutils.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

What could be the problem?

**Comment by nyanmn** [comment]
I have cython 0.27.1 version installed.

**Comment by ftian1** [comment]
it's weird, we never met such issue.

**Comment by ftian1** [comment]
could you list all python packages you installed through pip? such as numpy and cython.

**Comment by ftian1** [comment]
another thing to be aware of is we only tested on python2 rather python3.

**Comment by nyanmn** [comment]
Thanks for the fast response. I settled with pip install -U cython. It installed 0.29 version and no more error.
