### ISSUE TITLE
Error running bvlc_reference_caffenet with USE_MKL2017_AS_DEFAULT_ENGINE turned on

### ISSUE THREAD

**Issue by nickltj86** [intel/caffe#25]
**Build Configuration:**
Default Makefile.config with the delta below:
```
CPU_ONLY := 1
USE_MKL2017_AS_DEFAULT_ENGINE := 1
USE_OPENMP := 0

```
GCC version 4.8.4 on Ubuntu 14.04. Dual Socket CPU E5-2699 v4.

**Other environment variables:**
```
export MKL_NUM_THREADS=44
export MKL_DYNAMIC=false
export KMP_AFFINITY=granularity=fine,compact,1,0
```

`make runtest`
[==========] 1262 tests from 174 test cases ran. (98678 ms total)
[  PASSED  ] 1262 tests.

`./build/tools/caffe time -model models/bvlc_reference_caffenet/deploy.prototxt`
Above command completes successfully.

`./build/examples/cpp_classification/classification.bin ./models/bvlc_reference_caffenet/deploy.prototxt ./models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel ./test_files/mean.binaryproto ./test_files/synset_words.txt ./examples/images/cat.jpg`
Above command fails with the log below:

--------- Prediction for ./examples/images/cat.jpg ----------
F1121 18:54:31.096916 177833 mkl_memory.cpp:196] Check failed: status == 0 (-1 vs. 0) Conversion from prv failed with status -1
*** Check failure stack trace: ***
    @     0x7ff3266d2daa  (unknown)
    @     0x7ff3266d2ce4  (unknown)
    @     0x7ff3266d26e6  (unknown)
    @     0x7ff3266d5687  (unknown)
    @     0x7ff326aba764  caffe::MKLMemoryDescriptorBase<>::convert_from_prv()
    @     0x7ff326ab8512  caffe::SyncedMemory::cpu_data()
    @     0x7ff326bfe062  caffe::Blob<>::cpu_data()
    @     0x7ff326b85369  caffe::InnerProductLayer<>::Forward_cpu()
    @     0x7ff326be3f62  caffe::Net<>::ForwardFromTo()
    @     0x7ff326be41b5  caffe::Net<>::Forward()
    @     0x563d1bb2bc8e  Classifier::Predict()
    @     0x563d1bb2be24  Classifier::Classify()
    @     0x563d1bb2a309  main
    @     0x7ff3250eef45  (unknown)
    @     0x563d1bb2a8c0  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by nickltj86** [comment]
Also to note, did not install MKL. Only using the one downloaded using prepare_mkl.sh script.

**Comment by jczaja** [comment]
Thanks very much for your report, We are testing fix to similar issue. Problem is with Reshape function of MKLConvolution layer that manifest itself when blob (with data to be classied) is reshaped , so then Whole net is Reshaped . Is this your case eg. are you calling Reshape on your blob with data for classification ?

**Comment by nickltj86** [comment]
I believe so. When calling Predict, Reshape is called for the whole net.

**Comment by jczaja** [comment]
Beginning of next week we will push changes that should fix that issue. Stay tuned!

**Comment by jczaja** [comment]
We have just pushed some changes that should fix an isue You are seeing. Please sync and retest and let us know if issue is still there

**Comment by nickltj86** [comment]
Thanks. I will give it a try soon when i get machine time back.

**Comment by nickltj86** [comment]
@jczaja i have tested it and it works now, with much better performance than without MKL2017.
