### ISSUE TITLE
question about code in scripts/calibrator.py

### ISSUE THREAD

**Issue by SharpShip** [intel/caffe#251]
I refered to caffe API document, but didn't find relu in convolution_param.
Therefore, I'm a bit confused about the if statement.
Looking forward to your reply!

``
line 119: if layer.convolution_param.relu
``

**Comment by ftian1** [comment]
this->layer_param_.convolution_param().relu();

you can refer to mkldnn_convolution_layer.cpp for details.

**Comment by SharpShip** [comment]
Thx!
And I find the relu parameter in the caffe.proto file.
`
1141. optional bool relu = 19 [default = false]
`
