### ISSUE TITLE
intelcaffe time longer when clear cache,  so run intelcaffe with cached images or clear cache?

### ISSUE THREAD

**Issue by denniswuster** [intel/caffe#27]
The prefetch_batch will take long time after clearing cache which has the same behavior as the first run intelcaffe after reboot. 

Here is the experiment we have done:
1.	Change the Makefile.config to enable the DEBUG:=1 and rebuild the caffe application
2.	Run the intelcaffe with cache cleared:   “echo 3 > /proc/sys/vm/drop_caches” , you will see the forward time increase a lot. 
I1206 16:36:56.981101 23659 image_data_layer.cpp:231] Prefetch batch: 289 ms
3.	Run the caffe application again and most the images has already been loaded into the memory, now forward time decrease and consistent. 
I1206 16:50:49.657346 24815 image_data_layer.cpp:231] Prefetch batch: 20 ms.

So need to confirm how we run the intelcaffe, clear cache before running or run the intelcaffe with cached images??

**Comment by jczaja** [comment]
I'm not quite sure why are you telling OS to drop caches? If OS caches are dropped then yes caffe may work slower as OS caches will take time to be refilled with images. So what is in your opinion adventage of dropping caches?

**Comment by pnoga** [comment]
No response - closing.
