### ISSUE TITLE
classifier with the reference caffe model will crash

### ISSUE THREAD

**Issue by denniswuster** [intel/caffe#28]
./build/examples/cpp_classification/classification.bin  models/bvlc_reference_caffenet/deploy.prototxt   models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel   data/ilsvrc12/imagenet_mean.binaryproto   data/ilsvrc12/synset_words.txt   examples/images/cat.jpg
---------- Prediction for examples/images/cat.jpg ----------
Segmentation fault (core dumped)

with the gdb, it will show crashed:
(gdb) bt
#0  0x00007ffece1b40ae in parallel_doConversion_Simple_To_PCLData ()
    at /opt/intel/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64_lin/libmkl_avx512_mic.so
#1  0x00007ffedce9227b in mkl_dnn_do_parallel_F32 ()
    at /opt/intel/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so
#2  0x00007ffff141ad13 in __kmp_invoke_microtask ()
    at /opt/intel/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin/libiomp5.so
#3  0x00007ffff13eab17 in __kmp_invoke_task_func (gtid=-1564475328)
    at ../../src/kmp_runtime.c:7084
#4  0x00007ffff13ea1c5 in __kmp_launch_thread (this_thr=0x7ffea2c00040)
    at ../../src/kmp_runtime.c:5680
#5  0x00007ffff141b193 in _INTERNAL_24_______src_z_Linux_util_c_3e0095e6::__kmp_launch_worker(void*) (thr=0x7ffea2c00040) at ../../src/z_Linux_util.c:664
#6  0x00007ffff22dddc5 in start_thread () at /usr/lib64/libpthread.so.0
#7  0x00007ffff1df51cd in clone () at /usr/lib64/libc.so.6
(gdb) q

Anybody know how to solve this issue?

**Comment by nickltj86** [comment]
Not sure if this is related to #25  which was fixed. May be a different issue. dont see these exact issues

**Comment by jczaja** [comment]
Thanks for your report. We will shortly look at this.

**Comment by tsocha** [comment]
Can you give us some more information about:
-How did u build it.
-Processor model.
-Versions of used libraries.
-Git SHA-1 used to compile.

**Comment by pnoga** [comment]
no response - closing
