### ISSUE TITLE
is there  any performance benchmark ?

### ISSUE THREAD

**Issue by sunshinemyson** [intel/caffe#29]
1. any  benchmark with i-serial CPUs?
2. any benchmark compare with CUDA/CUDNN ?

**Comment by jdukat** [comment]
Our primary optimization targets are server platforms with Intel(r) Xeon(tm) and Intel(r) Xeon Phi(tm) processor families.
Although the code is generic enough to run on any modern client processors with Advanced Vector Extensions 2 (AVX2).
We do not publish any benchmarks on Intel distribution of Caffe* project pages and don't plan to do it in the future. Please refer to Intel marketing materials and other sources, like webinars, whitepapers and third party sites for benchmark results and competitive analysis.
https://newsroom.intel.com/news-releases/intel-ai-day-news-release/
https://software.intel.com/en-us/ai/deep-learning
