### ISSUE TITLE
Failed to Build caffe with Makefile

### ISSUE THREAD

**Issue by hensonwells** [intel/caffe#298]
**Issue :
Build caffe with Makefile  stop by libopencv_videoio.so.3.2: error adding symbols **
anybody could help?
details:
ssd_detect.o: undefined reference to symbolCXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/get_image_size.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
CXX/LD -o .build_release/tools/create_label_map.bin
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX/LD -o .build_release/tools/finetune_net.bin
CXX/LD -o .build_release/tools/net_speed_benchmark.bin
CXX/LD -o .build_release/tools/test_net.bin
CXX/LD -o .build_release/tools/train_net.bin
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
CXX/LD -o .build_release/tools/device_query.bin
CXX/LD -o .build_release/examples/ssd/ssd_detect.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
/usr/bin/ld: .build_release/examples/ssd/ssd_detect.o: undefined reference to symbol '_ZN2cv12VideoCaptureD1Ev'
//usr/lib/x86_64-linux-gnu/libopencv_videoio.so.3.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:629：.build_release/examples/ssd/ssd_detect.bin]  Error 1
make: *** Waiting for unfinished jobs....

**Comment by avinmaulana** [comment]
on makefile.config , change the opencv version to 3
install opencv3

**Comment by ftian1** [comment]
pls use cmake rather make. if you have to use make, pls update makefile.template to reflect your real env.
