### ISSUE TITLE
Failed while compiling matcaffe

### ISSUE THREAD

**Issue by avinmaulana** [intel/caffe#299]
Hello, everyone.
I've already compiled the caffe, make all make test and make runtest run without any error.
The problem is after i want to make the matcaffe.
I already set the path of matlab directory.
Im using ubuntu 18.04, with gcc 7.4, and matlab R2014b
Turns out it is error when i make the matcaffe. The error shows that the gcc version is not supported by the mex (mex only support 4.7.x)
I tried to downgrade the gcc and g++ into 4.7, but heres the thing i wondered:
1. I cant found the gcc 4.7, the apt search only show >4.8
2. im using cuda 10, and the supported gcc on cuda 10 documentation is version 7.3

Any ideas for what should i do?
Thanks for the help

**Comment by ftian1** [comment]
pls use BVLC caffe to matlab related development task. IntelCaffe doesn't ensure the functionality of mat caffe.
