### ISSUE TITLE
doesnt pick up OMP_NUM_THREADS

### ISSUE THREAD

**Issue by shayanshams66** [intel/caffe#30]
Hi
I am trying to run intell caffe on KNL as a host but it doesnt pick up OMP_NUM_THREADS and it just run it in a single thread. I am sure that It is compile with use_openmp
any suggestion?

**Comment by sidkashyap** [comment]
Make sure that you are using the right flags to compile (-qopenmp) and you can also turn on the KMP_AFFINITY=verbose environment variable to check the thread mapping.
