### ISSUE TITLE
how to find the difference between the original version and this one

### ISSUE THREAD

**Issue by anguoyang** [intel/caffe#33]
Hi, I want to learn how to improve performance on intel CPUs, so I need to compare the original copy and this one to find out how to do sth to improve performance on my program, when using intel cpu.

**Comment by jczaja** [comment]
If by "original copy" you mean BVLC/caffe and by "this one" you mean intel/caffe then you could
check performance by using "time" opetion of caffe tool to see average performance of diffrent
primitives executed for given model eg. for bvlc_reference_caffenet (this require setting up ImageNet)

**./build/tools/caffe time --model models/bvlc_reference_caffenet/train_val.prototxt --iterations=100 --engine CAFFE**

**./build/tools/caffe time --model models/bvlc_reference_caffenet/train_val.prototxt --iterations=100 --engine MKL2017**

And do similar commandline for bvlc/caffe:
**./build/tools/caffe time --model models/bvlc_reference_caffenet/train_val.prototxt --iterations=100**

You can start with smaller model like mnist or cifar that is easier to set up (dataset is to be downloaded via provided scripts)

Hope this will help

**Comment by anguoyang** [comment]
Sorry for the late response, actually, I do believe that Intel caffe will have much better performance over the original one on Intel CPUs, however, what I want, is to learn how to improve software performance on OpenCL/Intel, maybe not on caffe, but Intel/caffe will be a good example for me to learn. So, I want to compare the original one and the Intel/caffe, to find out what is the difference, then I could learn a lot on it.

I have plan to port other deep learning softwares from Cuda to Intel/openCL, as I have interest on Intel/opencl/FPGAs, Intel/caffe could be a good reference. 

Thank you.

**Comment by jdukat** [comment]
The best resource for OpenCL learning with Caffe will be the opencl branch on BVLC Caffe:
[(https://github.com/BVLC/caffe/tree/opencl)]
