### ISSUE TITLE
bvlc_googlenet performance problem with AVX512 on KNL with MKL2017

### ISSUE THREAD

**Issue by akeygma** [intel/caffe#35]
When test bvlc_googlenet performance with Intel caffe+MKL2017 on KNL, performance is impacted by AVX512

When turn on AVX512 path forward time is 326ms with batch size=32, and when turn off AVX512 and turn on AVX2 path, forward time is 140ms.

A layer by layer performance comparison shows there are performance penalty with AVX512 on inception_4c and inception_4b layers (the first number is AVX512 (ms), the second number is AVX2 (ms)), batch size is 256.

Performance scaling between AVX512 and AVX2 does works on bvlc_alexnet, vgg16 and vgg19, it only have problem with bvlc_googlenet.

294.061 inception_4c/5x5_reduce forward: 295.612 1.5508
301.966 inception_4b/5x5_reduce forward: 303.554 1.5879
565.386 inception_4c/5x5        forward: 567.578 2.1916
565.529 inception_4b/5x5        forward: 567.842 2.3125
1205.41 inception_4b/5x5_reduce backward: 1211.83 6.4179
1206.53 inception_4c/5x5_reduce backward: 1212.96 6.4257
3127.84 inception_4c/5x5        backward: 3133.31 5.471
3127.93 inception_4b/5x5        backward: 3133.64 5.7065

**Comment by pnoga** [comment]
Thanks for feedback. We are planing to make new release of Intel distribution of Caffe + new MKL2017 update 2 within next few weeks. All those problems should be solved and new performance on AVX512 will be achieved.

**Comment by pnoga** [comment]
New Caffe release is ready. Please check current performance on default/bvlc googlenet topology folder: /models/

**Comment by akeygma** [comment]
Verified the new Caffe, performance back to normal with AVX512, and 2x faster than AVX2, thanks!

**Comment by fengyuleidian0615** [comment]
Hi @akeygma and @pnoga 

I have downloaded the latest intelcaffe, may I ask how to switch between AVX512 and AVX2 to compare the performance?

thanks！
