### ISSUE TITLE
Intelcaffe will not build with CUDnn enabled

### ISSUE THREAD

**Issue by kgilov** [intel/caffe#41]
When enable CUDnn ( disable CPU_ONLY), build fail with 'undefined references' in MLSL and MPI.

This is due to error in Makefile:
change on line 250 
 ifneq ($(CPU_ONLY), 1)
         INCLUDE_DIRS += $(CUDA_INCLUDE_DIR)
         LIBRARY_DIRS += $(CUDA_LIB_DIR)
(-)        LIBRARIES := cudart cublas curand
(+)       LIBRARIES += cudart cublas curand
 endif

The change is on line 250 of the Makefile. The reason to change is when CPU_ONLY is not set, LIBRARY variable is reset to cuda libs ONLY and all previous libraries are lost. It should be inclusive, add the cuda libs to existing list.

--

**Comment by michalkuligowski** [comment]
Thank you for reporting this, we will look at this shortly

**Comment by apwojcik** [comment]
MLSL is pure CPU solution, it does not work with CUDnn. To resolve your issue please comment out USE_MLSL:=1 in Makefile.config or set the value of USE_MLSL:=0.

**Comment by kgilov** [comment]
thank you. We will use CPU_ONLY then.

BTW, I was able to compile with USE_CUDA, and will try to see what happen.

cheers,

--
