### ISSUE TITLE
Performance of Intel Caffe latest code

### ISSUE THREAD

**Issue by bage613** [intel/caffe#43]
Hi,
When I update Intel Caffe yesterday, I found flag param_server is not supported. You disable flag param_server, why? I tested multinode with MLSL using below command:
mpirun -n 4 -ppn 1 -machinefile /home/spark/mpd.hosts ./build/tools/caffe train --solver=models/intel_optimized_models/googlenet/solver.prototxt
Is that right?
In 4 KNL nodes, the FPS is 35.45*4 while single node FPS is 61.31. Detailed parameters are as below:
CPU: Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz
Memory: 16GB*6
HT off
Turbo on
export OMP_NUM_THREADS=64
export KMP_AFFINITY="verbose, none"
export MIC_KMP_AFFINITY="verbose, none"
batchsize=96
Can you give me the benchmark data and detailed parameters with latest code on XEON and XEON Phi?  Because I don't know whether my performance data is normal or not. Thank you!

**Comment by apwojcik** [comment]
Intel(R) Distribution of Caffe changed communication library to Intel(R) Machine Learning Scaling Library and parameter server is no longer in use (all nodes are autonomous). Therefore the command line option has been removed just not to introduce confusion (actually all command line parameters related to the previous communication library have been removed).
The command line you use and OMP_NUM_THREADS are correct. However for better performance please use MKL 2017 BLAS engine by adding --engine=MKL2017 to the command line options (multi-node user guide has been updated) and please change KMP_AFFINITY to:

`"proclist=[0-5,$((5+numservers+1))-$((maxcores-1)),$((maxcores))- \
$((maxcores+5)),$((maxcores+5+numservers+1))-$((2*maxcores-1))],granularity=thread,explicit"`

`numserver` = number of EP servers (env variable MLSL_NUM_SERVERS)

As for the official benchmark data please contact Intel's marketing representative.
