### ISSUE TITLE
Errors in latest code of Intel Caffe

### ISSUE THREAD

**Issue by bage613** [intel/caffe#45]
Hi,
I tested Intel Caffe latest code with MLSL on XEON Phi. In 4 nodes, it will crash when iterations at 320, below is the log:
I0207 20:34:07.109974 67930 blocking_queue.cpp:87] Waiting for data
*** Aborted at 1486517656 (unix time) try "date -d @1486517656" if you are using GNU date ***
PC: @     0x7f0e3913ef0b __memcpy_avx512_no_vzeroupper
*** SIGBUS (@0x7e067c17cfe1) received by PID 67743 (TID 0x7f0526ff4700) from PID 2081935329; stack trace: ***
    @     0x7f0e39471370 (unknown)
    @     0x7f0e3913ef0b __memcpy_avx512_no_vzeroupper
    @     0x7f0e39cf657e (unknown)
    @     0x7f0e39cf65ed (unknown)
    @     0x7f0e3dbb3b0a caffe::db::LMDBCursor::value()
    @     0x7f0e3da3696e caffe::DataReader::DBSequential::value()
    @     0x7f0e3da354fc caffe::DataReader::Body::read_one()
    @     0x7f0e3da360f4 caffe::DataReader::Body::InternalThreadEntry()
    @     0x7f0e3a15127a (unknown)
    @     0x7f0e39469dc5 start_thread
@     0x7f0e3919873d __clone
The environment info is : 
CPU: XEON Phi 7250 @ 1.40GHz
Memory: 32G*6
batichsize: 96
Running scripts is:
mpirun -n 4 -ppn 1 -machinefile ~/mpd.hosts ./build/tools/caffe train -solver models/intel_optimized_models/googlenet/solver.prototxt -engine MKL2017
However, it will run well on server with 16G*6 memory, while the other environment all the same.
Thank you for your help, hope to get help ASAP.

**Comment by apwojcik** [comment]
Please set environmental variable MLSL_HEAP_SIZE_GB=64 before training. Current MLSL is 2017 beta release. The gold release planned end of Q1'17 will have this fixed.

**Comment by bage613** [comment]
@apwojcik Thank you for your reply! Sorry for late. I run MLSL_HEAP_SIZE_GB=64 before training, but crash still exists. Recently I test RestNet50, there is same error when training. BTW, when will gold release release?
Thank you again!
