### ISSUE TITLE
Multi-node Training

### ISSUE THREAD

**Issue by fastalgo** [intel/caffe#46]
Is there any paper or report about how Intel Caffe conducts multi-node processing?

E.g. the way of communication, data partition, communication frequency, strong scaling efficiency.

Is Intel Caffe using the same idea of Parameter Sever (J. Dean, NIPS 2012)?

**Comment by pnoga** [comment]
Please start with our guide: https://github.com/intel/caffe/wiki/Multinode-guide

**Comment by fastalgo** [comment]
I mean, how the distributed-memory code (e.g. MPI) is implemented?

**Comment by apwojcik** [comment]
Intel(R) Distribution of Caffe is using Intel(R) Machine Learning Scaling Library for multi-node processing. Please ask this question to MLSL team via GitHub https://github.com/01org/MLSL.
