### ISSUE TITLE
Some remarks for the "Multinode guide" wiki

### ISSUE THREAD

**Issue by itemko** [intel/caffe#49]
1.
"caring out"
->
"carrying out"

2.
"The OS image can be downloaded free of charge from the official website. "
Broken link.

3.
"Refer to MLSL Wiki or "MLSL Developer Guide and Reference" for more details on the library."
MLSL wiki isn't ready yet - could you please remove it and mention "MLSL Developer Guide and Reference" as a hyperlink to https://github.com/01org/MLSL/blob/master/doc/Developer_Guide_and_Reference.pdf

4.
"$ yum upgrade" and others.
I suppose yum command requires privileged access so the command should look like "# yum upgrade" (or via sudo).

5.
"$ ansible all -m shell -a 'rpm -i ~/intel-mlsl-devel-64-2017.0-006.x86_64.rpm'"
Does this command work fine without PUBLIC_KEY.PUB importing?

6.
"$ source /opt/intel/mlsl_2017.0.003/intel64/bin/mlslvars.sh"
There should be 2017.0.006 version. Maybe to add MLSL version placeholder?

7.
"~/mpd.hosts"
->
"~/mpi.hosts"
Please rename it because MPD is an obsolete Intel MPI process manager.

**Comment by fzou1** [comment]
I have updated wiki with item 1,2, 3, 4, 6. 
for 5, yes. it can work without the pub file.
for 7, the file is used to include IP address or host name of nodes.
