### ISSUE TITLE
Build error in latest pull - boost

### ISSUE THREAD

**Issue by nickltj86** [intel/caffe#50]
CXX/LD -o .build_release/tools/caffe.bin
CXX/LD -o .build_release/tools/finetune_net.bin
CXX/LD -o .build_release/tools/create_label_map.bin
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
CXX/LD -o .build_release/tools/convert_annoset.bin
CXX/LD -o .build_release/tools/train_net.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/get_image_size.bin
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/tools/net_speed_benchmark.bin
CXX/LD -o .build_release/tools/test_net.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX/LD -o .build_release/tools/device_query.bin
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
CXX/LD -o .build_release/examples/ssd/ssd_detect.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
/usr/bin/ld: .build_release/examples/ssd/ssd_detect.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [.build_release/examples/ssd/ssd_detect.bin] Error 1
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.

Seems like there is a linker issue to boost? Any help to resolve this issue is much appreciated.

**Comment by nickltj86** [comment]
building the original ssd from weiliu works on the same machine

**Comment by tpatejko** [comment]
In your Makefile, you should put $(BOOST_LDFLAGS) in the EXAMPLES_BIN target. The $(BOOST_LDFLAGS) should go before $(LINKFLAGS) and after the name of the output. 

EXAMPLES_BIN target should be around 810 line in the original Makefile.

The problem is known and it will be corrected in the next release.

**Comment by nickltj86** [comment]
That fixes it. Thank you!
