### ISSUE TITLE
Compilation error with latest code in mkl_dnn_cppwrapper.h

### ISSUE THREAD

**Issue by sampathchanda** [intel/caffe#51]
With latest checkout of, while trying to build, I am seeing multiple compilation issues. One of them is the following:

In file included from /home/u2205/GitHub/intelcaffe/caffe/include/caffe/mkl_memory.hpp:48:0,
                 from /home/u2205/GitHub/intelcaffe/caffe/include/caffe/layers/mkl_layers.hpp:52,
                 from /home/u2205/GitHub/intelcaffe/caffe/src/caffe/layers/mkl_pooling_layer.cpp:45:
/home/u2205/GitHub/intelcaffe/caffe/include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateForward(_uniPrimitive_s**, dnnPrimitiveAttributes_t, dnnLayout_t, float, unsigned int) [with Dtype = float; dnnPrimitive_t = _uniPrimitive_s*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = _dnnLayout_s*]’:
/home/u2205/GitHub/intelcaffe/caffe/include/mkl_dnn_cppwrapper.h:797:31: error: ‘dnnBatchNormalizationCreateForward_v2_F32’ was not declared in this scope
         dataLayout, eps, flags); }

Is anyone else facing the issue ?
Can you please resolve this issue.

**Comment by Rpona** [comment]
I also meet multiple compilation issue. Any suugessions? 
A part of log:
/caffe/src/caffe/layers/mkldnn_inner_product_layer.cpp(75): error: no instance of constructor "boost::shared_ptr<T>::shared_ptr [with T=mkldnn::memory]" matches the argument list   argument types are: (long) fwd_top_data_memory(NULL),
...
compilation aborted for /caffe/src/caffe/layers/mkldnn_inner_product_layer.cpp
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_inner_product_layer.cpp.o] Error 2
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2 
make: *** [all] Error 2

**Comment by mblokker** [comment]
@sampathchanda I think I solved that error by replacing the 3 includes (starting on https://github.com/intel/caffe/blob/master/include/mkl_dnn_cppwrapper.h#L44) with absolute filepaths.

In your case, probably:
`#include "/home/u2205/GitHub/intelcaffe/caffe/external/mkl/mklml_lnx_2017.0.2.20170110/include/mkl_dnn_types.h"`
`#include "/home/u2205/GitHub/intelcaffe/caffe/external/mkl/mklml_lnx_2017.0.2.20170110/include/mkl_dnn.h"`
`#include "/home/u2205/GitHub/intelcaffe/caffe/external/mkl/mklml_lnx_2017.0.2.20170110/include/mkl_version.h"`

**Comment by sampathchanda** [comment]
@mblokker Thanks !! that worked.

Am testing with installed caffe now, seeing some other issues like:
I0219 23:41:42.858008 79322 data_transformer.cpp:64] Loading mean file from: data/ilsvrc12/imagenet_mean.binaryproto
F0219 23:41:42.870731 79323 db_lmdb.hpp:53] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @     0x7eff9aaa8e6d  (unknown)
    @     0x7eff9aaaaced  (unknown)
    @     0x7eff9aaa8a5c  (unknown)
    @     0x7eff9aaab63e  (unknown)
    @     0x7eff9bc052a1  caffe::db::LMDB::Open()
    @     0x7eff9ba02feb  caffe::DataReader::DBWrapper::DBWrapper()
    @     0x7eff9ba03a72  caffe::DataReader::Body::InternalThreadEntry()
    @     0x7eff9b41024a  (unknown)
    @     0x7eff9acd4dc5  start_thread
    @     0x7eff9128221d  __clone
./examples/imagenet/train_caffenet.sh: line 41: 79322 Aborted                 ./build/tools/caffe train --solver=models/bvlc_reference_caffenet/solver.prototxt $@

Any idea, how to fix it ?

**Comment by mblokker** [comment]
The error is clear, it fails to open the imagenet_mean.binaryproto file because it can't find it. Maybe you can find your info here: https://github.com/BVLC/caffe/tree/master/examples/imagenet#compute-image-mean
