### ISSUE TITLE
What is the possible reason of this bug?

### ISSUE THREAD

**Issue by fastalgo** [intel/caffe#55]
I0224 22:56:54.819372 29338 net.cpp:311] label_mnist_1_split does not need backward computation.
I0224 22:56:54.819403 29338 net.cpp:311] mnist does not need backward computation.
I0224 22:56:54.819428 29338 net.cpp:353] This network produces output accuracy
I0224 22:56:54.819458 29338 net.cpp:353] This network produces output loss
I0224 22:56:54.819519 29338 net.cpp:367] Network initialization done.
I0224 22:56:54.819759 29338 solver.cpp:106] Solver scaffolding done.
I0224 22:56:54.819890 29338 caffe.cpp:311] Configuring multinode setup
I0224 22:56:54.820473 29338 caffe.cpp:318] Starting Multi-node Optimization in mpi environment
I0224 22:56:54.820538 29338 SynchronousNode.cpp:603] [0] [proc 0] solving
I0224 22:56:54.820575 29338 solver.cpp:348] Solving LeNet
I0224 22:56:54.820600 29338 solver.cpp:349] Learning Rate Policy: inv
I0224 22:56:54.822309 29345 SynchronousNode.cpp:271] [0] Comm thread started 0 1
F0224 22:56:54.829016  1494 data_transformer.cpp:283] Check failed: channels == datum_channels (1 vs. 0) 
    @     0x2aaaaafd1a29 caffe::DataLayer<>::load_batch()
*** Aborted at 1488005814 (unix time) try "date -d @1488005814" if you are using GNU date ***
    @     0x2aaab02e78c6 _INTERNAL_23_______src_kmp_tasking_c_748e5a98::__kmp_invoke_task()
    @     0x2aaab02e7f1a __kmp_execute_tasks_64
*** Check failure stack trace: ***
    @     0x2aaab0297a1f _INTERNAL_25_______src_kmp_barrier_cpp_1d20fae8::__kmp_hyper_barrier_release()
    @     0x2aaab02991d8 __kmp_fork_barrier()
    @     0x2aaaad3fba7b  google::LogMessage::Flush()
    @     0x2aaab02c2110 __kmp_launch_thread
PC: @     0x2aaaab3c22fd caffe::DataTransformer<>::Transform()
*** SIGSEGV (@0x4c) received by PID 1485 (TID 0x2aac14803480) from PID 76; stack trace: ***
    @     0x2aaaad3fc3fd  google::LogMessageFatal::~LogMessageFatal()
    @     0x2aaaada69870 (unknown)
    @     0x2aaab02f3193 _INTERNAL_24_______src_z_Linux_util_c_3e0095e6::__kmp_launch_worker()
    @     0x2aaaada620a4 start_thread
    @     0x2aaab1b7002d __clone
    @     0x2aaaab3c22fd caffe::DataTransformer<>::Transform()
    @     0x2aaaab3c2ff8  caffe::DataTransformer<>::Transform()
    @     0x2aaaaafd1aab caffe::DataLayer<>::load_batch()
    @     0x2aaaaafd1aab  caffe::DataLayer<>::load_batch()
    @     0x2aaab02e78c6 _INTERNAL_23_______src_kmp_tasking_c_748e5a98::__kmp_invoke_task()
    @     0x2aaab02e78c6  _INTERNAL_23_______src_kmp_tasking_c_748e5a98::__kmp_invoke_task()
    @     0x2aaab02e7f1a __kmp_execute_tasks_64
    @     0x2aaab0297a1f _INTERNAL_25_______src_kmp_barrier_cpp_1d20fae8::__kmp_hyper_barrier_release()
    @     0x2aaab02e7f1a  __kmp_execute_tasks_64
    @     0x2aaab02991d8 __kmp_fork_barrier()
    @     0x2aaab0297a1f  _INTERNAL_25_______src_kmp_barrier_cpp_1d20fae8::__kmp_hyper_barrier_release()
    @     0x2aaab02c2110 __kmp_launch_thread
    @     0x2aaab02991d8  __kmp_fork_barrier()
    @     0x2aaab02f3193 _INTERNAL_24_______src_z_Linux_util_c_3e0095e6::__kmp_launch_worker()
    @     0x2aaaada620a4 start_thread
    @     0x2aaab02c2110  __kmp_launch_thread
    @     0x2aaab1b7002d __clone
I0224 22:56:54.823941 29345 SynchronousNode.cpp:431] [0] initialized root of cluster with nodes: 4 and the total iter size is: 4
*** Aborted at 1488005814 (unix time) try "date -d @1488005814" if you are using GNU date ***
PC: @     0x2aaaab3c22fd caffe::DataTransformer<>::Transform()
*** SIGSEGV (@0x4c) received by PID 29338 (TID 0x2aab61805780) from PID 76; stack trace: ***
    @     0x2aaaada69870 (unknown)
    @     0x2aaaab3c22fd caffe::DataTransformer<>::Transform()
    @     0x2aaaaafd1aab caffe::DataLayer<>::load_batch()
    @     0x2aaab02e78c6 _INTERNAL_23_______src_kmp_tasking_c_748e5a98::__kmp_invoke_task()
    @     0x2aaab02e7f1a __kmp_execute_tasks_64
    @     0x2aaab0297a1f _INTERNAL_25_______src_kmp_barrier_cpp_1d20fae8::__kmp_hyper_barrier_release()
    @     0x2aaab02991d8 __kmp_fork_barrier()
    @     0x2aaab02c2110 __kmp_launch_thread
    @     0x2aaab02f3193 _INTERNAL_24_______src_z_Linux_util_c_3e0095e6::__kmp_launch_worker()
    @     0x2aaaada620a4 start_thread
    @     0x2aaab1b7002d __clone
/global/u2/y/yyang420/caffe_run/mnist/./runscript_train_1.sh: line 3: 16220 Segmentation fault      caffe train --solver=lenet_solver1.prototxt --param_server=mpi
/global/u2/y/yyang420/caffe_run/mnist/./runscript_train_2.sh: line 3: 15775 Segmentation fault      caffe train --solver=lenet_solver2.prototxt --param_server=mpi
/global/u2/y/yyang420/caffe_run/mnist/./runscript_train_3.sh: line 3:  1485 Segmentation fault      caffe train --solver=lenet_solver3.prototxt --param_server=mpi
/global/u2/y/yyang420/caffe_run/mnist/./runscript_train_0.sh: line 3: 29338 Segmentation fault      caffe train --solver=lenet_solver0.prototxt --param_server=mpi
srun: error: nid03316: task 1: Exited with exit code 139
srun: Terminating job step 3856520.0
srun: error: nid03326: task 2: Exited with exit code 139
srun: error: nid03442: task 3: Exited with exit code 139
srun: error: nid03197: task 0: Exited with exit code 139

**Comment by michalkuligowski** [comment]
Hi, param_server was removed (Intel MLSL is now used as communication library), please try running without this parameter, also please refer to our Multinode guide https://github.com/intel/caffe/wiki/Multinode-guide. Could you tell where did you get net definisions from (to which point solver definitions - lenet_solverN.prototxt)? There are net definisions in this repo for mlsl defined here: https://github.com/intel/caffe/tree/master/examples/mnist
