### ISSUE TITLE
Support for MKLDNN is not enabled

### ISSUE THREAD

**Issue by mmx110** [intel/caffe#58]
Hi, 
when i use mkldnn, i get this problem "Support for MKLDNN is not enabled". 

Default Makefile.config with the delta below:
CPU_ONLY := 1
USE_MKLDNN_AS_DEFAULT_ENGINE := 1
USE_OPENMP := 0

but change USE_MKL2017_AS_DEFAULT_ENGINE := 1, and use mkl2017 is ok!

**Comment by haihaoshen** [comment]
Which topology did you use and what's the command?

**Comment by hshen14** [comment]
Please try latest version, which shall fix your issue.

**Comment by mmx110** [comment]
Ok, i will try.  thx !




发自网易邮箱大师


On 05/4/2017 09:37，Haihao Shen<notifications@github.com> wrote：

Please try latest version, which shall fix your issue.
