### ISSUE TITLE
Error while building with openBLAS

### ISSUE THREAD

**Issue by goodpp** [intel/caffe#6]
ubuntu12
CPU_ONLY := 1
BLAS := open

AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: .build_release/src/caffe/internode/tcp_configuration.o: relocation R_X86_64_TPOFF32 against `boost::asio::detail::keyword_tss_ptr<boost::asio::detail::call_stack<boost::asio::detail::task_io_service, boost::asio::detail::task_io_service_thread_info>::context>::value_' can not be used when making a shared object; recompile with -fPIC
.build_release/src/caffe/internode/tcp_configuration.o: could not read symbols: Bad value
collect2: ld returned 1 exit status
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

**Comment by jdukat** [comment]
Hi,
Thanks for reporting the problem. We are aware of this compilation issue - it is the same problem as in #2 
This will be fixed soon.

Recommended library for use with Intel Caffe is Intel MKL. MKL binaries are available for download without any special licensing, so I encourage you to try them. If you see any problems with MKL that force you to switch to openBLAS, please report them.

**Comment by jczaja** [comment]
@goodpp We have just introduced a fix that should adress the issue you are seeing. Please sync , retest and let us know if issue is gone. Thanks

**Comment by pnoga** [comment]
closing issue as fixed
