### ISSUE TITLE
Classifier from examples runs slower on first run

### ISSUE THREAD

**Issue by sergboec** [intel/caffe#61]
Hello!
I performed the classifier example on VGG_S network from caffe model zoo several times. 
In VGG profile there is no engine in convolutional layer parameters.
First run gives me speed about X (ms).
Second run was 10 times faster and speed remains stable.
If you explicitly set engine property to MKLDNN or MKL2017 speed will be stable no matter of run number.

So my question is: is this is a planned behaviour?
How it's made if it's a planned behaviour?

**Comment by daisyden** [comment]
When you met the issue, what is the engine for the first run when the speed is slow?

**Comment by hshen14** [comment]
Close it first due to no further information update.
