### ISSUE TITLE
EPEL 7.8 error

### ISSUE THREAD

**Issue by sergey-serebryakov** [intel/caffe#63]
Hi! 
Today I've tried to build a docker image (docker/standalone/cpu-centos/Dockerfile). The process failed due to unavailability of the epel-release-7-8.noarch.rpm package. It seems this version is not available anymore. However, version 7.9 is there: http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm.
Thanks!

**Comment by hshen14** [comment]
It is no an issue from Caffe side. Close it.
