### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Daenerys24** [intel/caffe#64]
When I try to import caffe for use with google deep dreams, I get this:

ImportError: libmkldnn.so: cannot open shared object file: No such file or directory

I have mkldnn installed to the correct directory in my OS. Locate libmkldnn.so shows:
/home/archpengown/Downloads/deepdream/caffe/external/mkldnn/build/src/libmkldnn.so
/home/archpengown/Downloads/deepdream/caffe/external/mkldnn/install/lib/libmkldnn.so
/home/archpengown/Downloads/intel-caffe/external/mkldnn/build/src/libmkldnn.so
/home/archpengown/Downloads/intel-caffe/external/mkldnn/install/lib/libmkldnn.so
/home/archpengown/Downloads/mkl-dnn/build/src/libmkldnn.so
/usr/local/lib/libmkldnn.so

Makefile.config includes /usr/local/lib with Python.

What am I missing :-/

**Comment by tpatejko** [comment]
With the newest release, Intel Caffe by default downloads MKLDNN from github, and builds it. Commit hash of MKLDNN that is used is stored in MKLDNN.commit file in Intel Caffe's root directory.

You have additional options:
1. You can set an environment variable MKLDNNROOT to point to the specific MKLDNN's distribution you want to use.
2. You can set MKLDNNROOT variable to an empty string, so MKLDNN is not build by Intel Caffe.

Let me know if that helps.

**Comment by Bugix-ZY** [comment]
@tpatejko 

> set MKLDNNROOT variable to an empty string

That works for me. Thanks a lot!

**Comment by MichaelOVertolli** [comment]
I found a similar error with weirder properties. Whenever I'm not in the base caffe folder (i.e., not the python one), I can import caffe in python no problem. But, when I'm anywhere else, I get the following error.

`>>> import caffe`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/home/mvertolli/caffe/python/caffe/__init__.py", line 37, in <module>`
`    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, Adamsolver`
`  File "/home/mvertolli/caffe/python/caffe/pycaffe.py", line 49, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \`
`ImportError: libmkldnn.so: cannot open shared object file: No such file or directory`

Any thoughts?

**Comment by hshen14** [comment]
Did you build Caffe successfully without specifying MKLDNNROOT? If so, you may specify LD_LIBRARY_PATH to the missing library and run again.

**Comment by hshen14** [comment]
Close it for environment issue

**Comment by himsR** [comment]
How to and where to set MKLDNNROOT variable to an empty string?

**Comment by tjucaokun** [comment]
@Daenerys24 Have you solved this problem? Can you teach me how to solve it ? Thank you!!!

**Comment by tjucaokun** [comment]
@Bugix-ZY
 Excuse me,
 how can I set MKLDNNROOT variable to an empty string?
