### ISSUE TITLE
mkl_concat_layer failure

### ISSUE THREAD

**Issue by jiangyurong609** [intel/caffe#65]
I'm trying to run SSD on my server for both training and testing, 
e.g. 
 "./build/tools/caffe test --model="/path/VGGNet/VOC0712/SSD_300x300_video/test.prototxt" --weights="models/VGGNet/VOC0712/SSD_300x300/VGG_VOC0712_SSD_300x300_iter_120000.caffemodel" --iterations="536870911"

Always get same error as below. 
Logs: 
F0328 11:57:01.972982 27491 mkl_concat_layer.cpp:250] Check failed: e == E_SUCCESS (-1 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f091ae4348a  google::LogMessage::Fail()
    @     0x7f091ae433ce  google::LogMessage::SendToLog()
    @     0x7f091ae42da0  google::LogMessage::Flush()
    @     0x7f091ae46121  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f091b3a92f4  caffe::MKLConcatLayer<>::Forward_cpu()
    @     0x7f091b5abf32  caffe::Net<>::ForwardFromTo()
    @     0x7f091b5ac147  caffe::Net<>::Forward()
    @     0x55918a3729d6  test()
    @     0x55918a36e88f  main
    @     0x7f0919eb3830  (unknown)
    @     0x55918a36f5b9  _start

Not sure why this part has problem, highly appreciated if someone can help

**Comment by tpatejko** [comment]
This is a known issue for SSD on Intel Caffe.

Right now, MKL2017 does not support a concat layer in the configuration that is used in SSD. 
Because of this issue, we build Intel Caffe for SSD with USE_MKL2017_AS_DEFAULT_ENGINE off, and with engines set manually in the prototxt files. You can have a look at the exemplary configurations in examples/ssd/VGGNet/VOC0712/SSD_300x300/:
https://github.com/intel/caffe/blob/master/examples/ssd/VGGNet/VOC0712/SSD_300x300/test.prototxt#L1619

**Comment by tpatejko** [comment]
Could you tell me how you built Intel Caffe? Do you use USE_MKL2017_AS_DEFAULT_ENGINE flag?

**Comment by jiangyurong609** [comment]
After I disabled USE_MKL2017_AS_DEFAULT_ENGINE, it can now work. But I'm not sure the current caffe is using MKL or MKL-DNN? How can I distinguish this?

**Comment by tpatejko** [comment]
You could set an engine in the prototxt file:
https://github.com/intel/caffe/blob/master/examples/ssd/VGGNet/VOC0712/SSD_300x300/test.prototxt

There's a certain hierarchy of how engine parameter is interpreted:
1. Legacy enum-based layer parameter (concat_param variable)
2. Command line switch: --engine=MKL2017
3. Engine defined in solver file
4. Engine defined in model
5. Layer engine that is set as a string

**Comment by jiangyurong609** [comment]
Thanks, so for "MKL2017" means "MKL", and "MKLDNN" for "MKLDNN"?

**Comment by tpatejko** [comment]
Yes, sort of. MKL2017 and MKLDNN are the names of engines that provide deep learning primitives optimized for CPUs.  MKL functions here as a prefix for layers optimized with MKL2017.

**Comment by hshen14** [comment]
Close it for enhancement
