### ISSUE TITLE
poor alexnet image inference perf at skylake when batchsize is 2, 4, 8 

### ISSUE THREAD

**Issue by moting9** [intel/caffe#66]
summary
=======
in skylake (28 core/socket， 2.5GHz) platform, 
with latest mkl version(20170325 build) and latest intel caffe
execute cmd: 
./build/tools/caffe time -model models/bvlc_alexnet/deploy.prototxt -iterations=200 -engine=MKL2017

batchsize	latency(ms)
1	       4.31032
2	       21.5232
4	       21.6148
8	       23.5313
16	       14.4938
32	       21.7228
64	       32.2652
128	       60.1997

The latency is abnormal when batchsize is 2/4/8,   fc layer consumes much time, the issue doesn't occur in BDW platform.

**Comment by moting9** [comment]
The issue doesn't occur in BDW and KNL, only occur in SKX.

**Comment by hshen14** [comment]
Close it for enhancement.
