### ISSUE TITLE
Performance for C and C++ is much different? Why?

### ISSUE THREAD

**Issue by heagoo** [intel/caffe#68]
I had a try for the 2 examples (simple_net.c, simple_net.cpp), and found the performance is much different.
Here is the data on Broadwell platform:
root@bdw:mkl-dnn# time ./build/examples/simple-net-c
passed

real    0m0.776s
user    0m9.444s
sys     0m0.810s
root@bdw:mkl-dnn# time ./build/examples/simple-net-cpp

real    0m0.273s
user    0m7.771s
sys     0m2.737s

**Comment by emfomenk** [comment]
Hi @heagoo,

simple-net-c contains several calls to `memset` while simple-net-cpp does not.
`memset` is sequential and that is main reason why `time` shows different performance.

The main purpose of simple nets (both C and C++) is to demonstrate MKL-DNN usage model (specifically, the work with data formats). These over-simple examples would not show the performance -- at least due the fact that there is only one computation per one creation step (while caffe creates primitives once and then reuses them many times).

If you want to look at performance of MKL-DNN I would suggest you either run `caffe time` for the topology you are interested in or take a look on standalone convolution benchmark [DeebBench](https://github.com/baidu-research/DeepBench) which supports both Intel MKL and MKL-DNN.

**Comment by heagoo** [comment]
That make sense. I just want to make sure that there is no performance decrease for the C code. Thanks for the explanation!
