### ISSUE TITLE
something wrong on Alexnet with dummy input

### ISSUE THREAD

**Issue by tensor-tang** [intel/caffe#69]
When using dummy data, Alexnet seems unexpectedly did not run bwd data on conv layer, comparing with LMDB input.

It should be something wrong the blob.

PS: engine: MKLDNN

**Comment by haihaoshen** [comment]
For deploy.prototxt using dummy data, there is no loss layer, so it will bypass layer propagate (backward).

**Comment by hshen14** [comment]
It is not an issue from Caffe side. Close it.
