### ISSUE TITLE
Something wrong use my net，but berkeleyvision is ok

### ISSUE THREAD

**Issue by jsa1988** [intel/caffe#70]
I0414 17:34:21.382794 35470 net.cpp:407] This network produces output loss5a/fc/feat/bn
I0414 17:34:21.383065 35470 net.cpp:500] Network initialization done.
I0414 17:34:21.384421 35470 caffe.cpp:534] Performing Forward
terminate called after throwing an instance of 'mkldnn::error'
  what():  std::exception
*** Aborted at 1492162463 (unix time) try "date -d @1492162463" if you are using GNU date ***
PC: @     0x7fb3b17c1c37 (unknown)
*** SIGABRT (@0x3e800008a8e) received by PID 35470 (TID 0x7fb3b387bac0) from PID 35470; stack trace: ***
    @     0x7fb3b17c1cb0 (unknown)
    @     0x7fb3b17c1c37 (unknown)
    @     0x7fb3b17c5028 (unknown)
    @     0x7fb3b20cc535 (unknown)
    @     0x7fb3b20ca6d6 (unknown)
    @     0x7fb3b20ca703 (unknown)
    @     0x7fb3b20ca922 (unknown)
    @     0x7fb3b3125bc2 mkldnn::error::wrap_c_api()
    @     0x7fb3b3128fbb caffe::MKLDNNInnerProductLayer<>::InitInnerProductFwd()
    @     0x7fb3b312a48e caffe::MKLDNNInnerProductLayer<>::Forward_cpu()
    @     0x7fb3b30f0a12 caffe::Net<>::ForwardFromTo()
    @     0x7fb3b30f0c47 caffe::Net<>::Forward()
    @     0x5624979e5cf8 time()
    @     0x5624979df02c main
    @     0x7fb3b17acf45 (unknown)
    @     0x5624979dfbdb (unknown)
    @                0x0 (unknown)

when call 
ipFwd_pd->bias_primitive_desc()    program crash

**Comment by daisyden** [comment]
May I know what is your topology?

**Comment by jsa1988** [comment]
@daisyden  can I have you email ，then I email to you？

**Comment by daisyden** [comment]
Hello jsa1988, daisy.deng@intel.com, Thanks!

**Comment by jsa1988** [comment]
@daisyden  I have emailed to you,please help me,Thanks
