### ISSUE TITLE
Build Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by tarun1325** [intel/caffe#71]
@matakk @pnoga @darxriggs @pohly @bobpoekert
[compileError.txt](https://github.com/intel/caffe/files/927416/compileError.txt)

Does compiling this on Ubuntu 14.04[trusty] work ?
I m getting a lot of errors on compiling this on ubuntu.

I have attached compilation log

for example:

In file included from ./include/caffe/blob.hpp:47:0,
from ./include/caffe/mkl_memory.hpp:45,
from src/caffe/mkl_memory.cpp:41:
./include/caffe/syncedmem.hpp: In function ‘void caffe::CaffeMallocHost(void**, size_t, bool*)’:
./include/caffe/syncedmem.hpp:72:10: error: ‘MLSL’ has not been declared
*ptr = MLSL::Alloc(size ? size : 1, 64);

**Comment by sidkashyap** [comment]
error: ‘MLSL’ has not been declared
*ptr = MLSL::Alloc(size ? size : 1, 64);
You need to ensure that MLSL is installed right and the include flags need to indicate that (if it is not present in the default search path). 

Also, try using the beta release of MLSL instead of the latest one, there are API compatibility issues.

**Comment by tarun1325** [comment]
Hello @sidkashyap , thanks for reply.
When I try to run the **latest MLSL** test example alone.
It works for me on a single node. 
But it doesn't work for multi node. As soon as i provide host_file.

**Comment by fzou1** [comment]
@tarun1325 Is the issue fixed? If no, did you install MLSL and run mlslvars.sh before building?

**Comment by tarun1325** [comment]
@fzou1 Issue is not fixed. Yes I did install MLSL and run mlslvars.sh

**Comment by fzou1** [comment]
it's an old version of caffe. please update to latest version of caffe and MLSL.

**Comment by hshen14** [comment]
The new Caffe version will deploy MLSL automatically. Please try the latest version.
