### ISSUE TITLE
Spelling error in MlsSync.hpp message

### ISSUE THREAD

**Issue by sfleisch** [intel/caffe#72]
W0418 13:03:38.129304 41040 MlslSync.hpp:137] RUN: **DITRIBUTED** WEIGHT UPDATE IS DISABLED, PER LAYER TIMINGS ARE DISABLED, SINGLE DB SPLITTING IS DISABLED

Should be **DISTRIBUTED**.

**Comment by fzou1** [comment]
The message is removed from latest caffe. I'd like to close this issue.
