### ISSUE TITLE
Crash for multiple SetGlobalMinibatchSize calls with dummy data

### ISSUE THREAD

**Issue by aprocter** [intel/caffe#74]
Caffe built with `USE_MLSL` crashes with the following error when running with dummy data:

```
I0426 23:27:44.540576  9778 layer_factory.hpp:114] Creating layer data
I0426 23:27:44.540695  9778 net.cpp:183] Creating Layer data
I0426 23:27:44.540752  9778 net.cpp:838] data -> data
W0426 23:27:44.540834  9778 net.cpp:247] SetMinibatchSize 256
I0426 23:27:44.617437  9778 net.cpp:267] Setting up data
I0426 23:27:44.617678  9778 net.cpp:274] Top shape: 256 3 227 227 (39574272)
I0426 23:27:44.618031  9778 net.cpp:282] Memory required for data: 158297088
I0426 23:27:44.618330  9778 layer_factory.hpp:114] Creating layer data
I0426 23:27:44.618635  9778 net.cpp:183] Creating Layer data
I0426 23:27:44.618927  9778 net.cpp:838] data -> label
W0426 23:27:44.619413  9778 net.cpp:247] SetMinibatchSize 256
(9778): mlsl_impl.hpp:SetGlobalMinibatchSize:779: ASSERT '!isBatchSizeSet' FAILED: minibatch size can be set only once 
```

Reported by @craftyguy.

To replicate, build with `USE_MLSL` and run this command:

```
$ caffe time -model train_val_dummy_b256.prototxt -engine MKL2017
```

where `train_val_dummy_b256.prototxt` is derived from `models/intel_optimized_models/alexnet/train_val.prototxt` by replacing the data layer with the following.

```
layer {
  name: "data"
  type: "DummyData"
  top: "data"
  #include {
  #  phase: TRAIN
  #}
  dummy_data_param {
    data_filler {
      type: "constant"
      value: 0.01
    }
    shape {
      dim: 256
      dim: 3
      dim: 227
      dim: 227
    }
  }
}
layer {
  name: "data"
  type: "DummyData"
  top: "label"
  #include {
  #  phase: TRAIN
  #}
  dummy_data_param {
    data_filler {
      type: "constant"
    }
    shape {
      dim: 256
    }
  }
}
```

**Comment by aprocter** [comment]
[train_val_dummy_b256.prototxt.txt](https://github.com/intel/caffe/files/960327/train_val_dummy_b256.prototxt.txt)

**Comment by jgong5** [comment]
Adam, it is a known issue and will be fixed soon. You may try the following patch to workaround the problem first:
diff --git a/src/caffe/net.cpp b/src/caffe/net.cpp
index 545a1f0..c936dd7 100644
--- a/src/caffe/net.cpp
+++ b/src/caffe/net.cpp
@@ -142,6 +142,9 @@ void Net<Dtype>::Init(const NetParameter& in_param) {
     fflush(0);
   }
 
+#ifdef USE_MLSL
+  int global_batch_size = -1;
+#endif
   // Basically, build all the layers and set up their connections.
   name_ = param.name();
   map<string, int> blob_name_to_idx;
@@ -245,7 +248,12 @@ void Net<Dtype>::Init(const NetParameter& in_param) {
 
         if (caffe::TRAIN == param.state().phase()) {
             LOG(WARNING) << "SetMinibatchSize " << batch_size;
-            mn::train::set_global_minibatch_size(batch_size * mn::get_nodes_count());
+            if (global_batch_size < 0) {
+              global_batch_size = batch_size * mn::get_nodes_count();
+              mn::train::set_global_minibatch_size(global_batch_size);
+            } else {
+              CHECK_EQ(global_batch_size, batch_size * mn::get_nodes_count());
+            }
         }
     }
 #endif /* USE_MLSL */

**Comment by craftyguy** [comment]
Thank you, I will give that a try and report back if there are any issues with it

**Comment by aprocter** [comment]
@hshen14: I don't think the patch that @jgong5 sent us was ever upstreamed. The bug still exists with the latest master rev. Applying the patch makes it go away. Can we reopen this?
