### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by tataki** [intel/caffe#75]
F0511 09:35:07.590688  8110 mkl_lrn_layer.cpp:215] Check failed: e == E_SUCCESS (-3 vs. 0) 
*** Check failure stack trace: ***
    @     0x2ae890e9edaa  (unknown)
    @     0x2ae890e9ece4  (unknown)
    @     0x2ae890e9e6e6  (unknown)
    @     0x2ae890ea1687  (unknown)
    @     0x2ae892c3b587  caffe::MKLLRNLayer<>::CrossChannelForward_cpu()
    @     0x2ae892c3a281  caffe::MKLLRNLayer<>::Forward_cpu()
    @     0x2ae892cc6302  caffe::Net<>::ForwardFromTo()
    @     0x2ae892cc6555  caffe::Net<>::Forward()
    @     0x55c96f003e6e  caffe::NetTestCPU_TestForwardReshapeForward_Test<>::TestBody()
    @     0x55c96f415263  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x55c96f409937  testing::Test::Run()
    @     0x55c96f4099de  testing::TestInfo::Run()
    @     0x55c96f409ae5  testing::TestCase::Run()
    @     0x55c96f40bb58  testing::internal::UnitTestImpl::RunAllTests()
    @     0x55c96f40be24  testing::UnitTest::Run()
    @     0x55c96ef348e2  main
    @     0x2ae8937bbf45  (unknown)
    @     0x55c96ef45472  (unknown)
    @              (nil)  (unknown)
Aborted
make: *** [runtest] Error 134

What reason is this when  running on Virtual Private Server?

**Comment by hshen14** [comment]
Please try again on real HW and reopen it if the issue does not disappear.
