### ISSUE TITLE
A mkldnn compiling bug when anaconda3 is used

### ISSUE THREAD

**Issue by luohaibiao** [intel/caffe#77]
In caffe-master/Makefile.config, I've defined anaconda3 as the Python library (detail can be seen from Makefile.config attachment), Note that anaconda3/lib path isn't defined in my environment library path. Only anaconda3/bin is defined in .bashrc. The Linux system is Red Hat Enterprise Linux Server release 6.5 (Santiago) on a supercomputer cluster.

When compiling caffe by command "make all", the following line was shown
-- Intel(R) MKL found: include /HOME/ac_iscas_hbluo_1/Intel_2017_3/compilers_and_libraries_2017.3.191/linux/mkl/include, lib **/HOME/ac_iscas_hbluo_1/local/anaconda3/lib/libmkl_rt.so**

Note that here MKL lib was refered to /HOME/ac_iscas_hbluo_1/local/anaconda3/lib/libmkl_rt.so

**The compiling stopped by the following error:**
[ 39%] Built target mkldnn
make[3]: Entering directory `/WORK/ac_iscas_hbluo_1/Intel_caffe/caffe-master_bk/external/mkldnn/build'
Scanning dependencies of target simple-training-net-cpp
make[3]: Leaving directory `/WORK/ac_iscas_hbluo_1/Intel_caffe/caffe-master_bk/external/mkldnn/build'
make[3]: Entering directory `/WORK/ac_iscas_hbluo_1/Intel_caffe/caffe-master_bk/external/mkldnn/build'
[ 40%] Building CXX object examples/CMakeFiles/simple-training-net-cpp.dir/simple_training_net.cpp.o
[ 40%] Linking CXX executable simple-training-net-cpp
../src/libmkldnn.so: undefined reference to `__cxa_throw_bad_array_new_length'
make[3]: *** [examples/simple-training-net-cpp] Error 1
make[3]: Leaving directory `/WORK/ac_iscas_hbluo_1/Intel_caffe/caffe-master_bk/external/mkldnn/build'
make[2]: *** [examples/CMakeFiles/simple-training-net-cpp.dir/all] Error 2
make[2]: Leaving directory `/WORK/ac_iscas_hbluo_1/Intel_caffe/caffe-master_bk/external/mkldnn/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/WORK/ac_iscas_hbluo_1/Intel_caffe/caffe-master_bk/external/mkldnn/build'
make: *** [mkldnn_build] Error 2

Now I replaced anaconda3 with Python 2.4.9 in Makefile.config, the above error disappeared. The make_output.log and Makefile.config are attached.

Any idea why anaconda3/lib/libmkl_rt.so was loaded as MKL library? How can I use anaconda3?

[Uploading make_output.txt…]()

**Comment by gtvforever** [comment]
Would you please re-upload your make_output.log and Makefile.config again?

**Comment by ftian1** [comment]
Anaconda default installation should not include mkl related libraries. you can try to uninstall mkl rt from anaconda at first and then rebuild intel caffe.

**Comment by hshen14** [comment]
Close it first and please raise it again if issue is still there.
