### ISSUE TITLE
make runtest error: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by luohaibiao** [intel/caffe#78]
caffe-master]$ make runtest 2>&1
.build_release/tools/caffe
make: *** [runtest] Illegal instruction (core dumped)

make all encountered one error about fwrite function error in gtest.c. I edited gtest.c according to mkldnn githup guideline. After that ,everything ran smoothly. 

There are some warnings in make test
./include/caffe/engine_parser.hpp(88): warning #1011: missing return statement at end of non-void function "caffe::EngineParser::getMKLDNNSubEngine"
    }
    ^
src/caffe/test/test_mkldnn_neuron_layers.cpp(119): warning #2196: routine is both "inline" and "noinline"
src/caffe/test/test_engine_selection.cpp(489): warning #2196: routine is both "inline" and "noinline"
....

The system is RedHat Enterprise 6.5. Run with CPU-only, no GPU installed. Any suggestion on where the problem might be?

**Comment by hshen14** [comment]
Close it and please raise it again if issue is there.
