### ISSUE TITLE
Does this repo include optimizations from clcaffe

### ISSUE THREAD

**Issue by atlury** [intel/caffe#8]
Hello
Are you considering including optimizations and changes from clcaffe? 
https://github.com/01org/caffe/wiki/clCaffe

In addition to speed up of caffe using AVX2 and like, opencl can also add to the performance.

Thank you

**Comment by jdukat** [comment]
Hi,
This is an option for the future - we consider adding support for Intel GEN and Windows OS later in 2017. But it is not decided yet and for the time being no integration work is in progress.
Note that https://github.com/01org/caffe is not actively maintained anymore. For the best OpenCL performance, please use the official OpenCL branch from BVLC Caffe:
https://github.com/BVLC/caffe/tree/opencl
Intel is actively contributing to that branch.
