### ISSUE TITLE
what is the role of blob->set_prv_data_descriptor(NULL);

### ISSUE THREAD

**Issue by HAIDJ** [intel/caffe#80]
Hello all,

I have a question in the source code of mkldnn.

Why does set_prv_data_descriptor call twice with different parameters in mkldnn_memory.cpp? 

`               blob->set_prv_data_descriptor(this->get_shared_ptr(), false);
`
.
 `       
                blob->set_prv_data_descriptor(NULL);
`
[please see 251-254 line](https://github.com/intel/caffe/blob/master/src/caffe/mkldnn_memory.cpp)
If set_prv_data_descriptor (NULL) is commented out, the processing speed of bwdd_top_diff-> sync_before_read ()  is improved in backward convolution. 

But, I wonder if this will give a reasonable result.

Thank you
Daejin Jung

**Comment by dxxz** [comment]
So in case of get_blob_prv_primitive , it is situation when blob does not contain private data, so we are to bind descriptor we created to that blob eg Blob._data contains only CPU_DATA
so we bind "First Line" created descriptor. This function unfortunately change the state of syncedmem of blob to HEAD_AT_PRV, which is a bit upfront as data is still in CPU_DATA only and no conversion was actually performed yet.
So this is a reason why there is a "Second Line" to move back state of head of data to HEAD_AT_CPU , so this will trigger conversion at sync_before_read.

**Comment by hshen14** [comment]
Will be available in upcoming release.
