### ISSUE TITLE
How to use Xeon Phi co-processor (like Knights Landing) to accelerate intel-caffe?

### ISSUE THREAD

**Issue by ganshaoduo** [intel/caffe#81]
Hi guys,

I noticed in release_notes.md file that this project can support Xeon Phi product family (codename: Knights Landing). I wonder how to use MIC co-processor to accelerate this project, like what GPU did. I'd like to deploy this project on a CPU-MIC heterogeneous system, where should I start? 

Thank you!

**Comment by hshen14** [comment]
Same as KNL processor.
