### ISSUE TITLE
MKLDNN Failed at caffe --time

### ISSUE THREAD

**Issue by HolmesShuan** [intel/caffe#87]
I0615 17:10:00.979809 25707 caffe.cpp:534] Performing Forward
I0615 17:10:01.346146 25707 caffe.cpp:539] Initial loss: 0
I0615 17:10:01.346202 25707 caffe.cpp:541] Performing Backward
I0615 17:10:01.346210 25707 caffe.cpp:550] *** Benchmark begins ***
I0615 17:10:01.346213 25707 caffe.cpp:551] Testing for 10 iterations.
I0615 17:10:02.041507 25707 caffe.cpp:580] Iteration: 1 forward-backward time: 695 ms.
*** Aborted at 1497517802 (unix time) try "date -d @1497517802" if you are using GNU date ***
PC: @     0x7fa605f30a58 _ZN6mkldnn4impl3cpu19simple_reorder_implIL18mkldnn_data_type_t1EL22mkldnn_memory_format_t5ELS3_1ELS4_8ELb0EvE7executeERKNS0_19memory_desc_wrapperES8_PKfPfdd._omp_fn.23
*** SIGSEGV (@0x55afbc091300) received by PID 25707 (TID 0x7fa5e6db4780) from PID 18446744072569295616; stack trace: ***
    @     0x7fa60dd454b0 (unknown)
    @     0x7fa605f30a58 _ZN6mkldnn4impl3cpu19simple_reorder_implIL18mkldnn_data_type_t1EL22mkldnn_memory_format_t5ELS3_1ELS4_8ELb0EvE7executeERKNS0_19memory_desc_wrapperES8_PKfPfdd._omp_fn.23
    @     0x7fa5ff549d13 __kmp_invoke_microtask
    @     0x7fa5ff519b17 __kmp_invoke_task_func
    @     0x7fa5ff5191c5 __kmp_launch_thread
    @     0x7fa5ff54a193 _INTERNAL_24_______src_z_Linux_util_c_3e0095e6::__kmp_launch_worker()
    @     0x7fa60dafa6ba start_thread
    @     0x7fa60de1682d clone
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by dxxz** [comment]
Would you please provide your command, and prototxt files for reproducing this issue?
In the internal test, we cannot reproduce this issue.

**Comment by HolmesShuan** [comment]
```name: "FSRCNN"
input: "data"
input_dim: 1
input_dim: 1
input_dim: 1000
input_dim: 1000

layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 0.1
  }
  convolution_param {
    num_output: 56
    kernel_size: 5
    stride: 1
    pad: 0
    weight_filler {
      type: "gaussian"
      std: 0.05
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}

layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  top: "conv1"
}

layer {
  name: "conv2"
  type: "Convolution"
  bottom: "conv1"
  top: "conv2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 0.1
  }
  convolution_param {
    num_output: 16
    kernel_size: 1
    stride: 1
	group: 1
    pad: 0
    weight_filler {
      type: "gaussian"
      std: 0.6325
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}

layer {
  name: "relu2"
  type: "ReLU"
  bottom: "conv2"
  top: "conv2"
}

layer {
  name: "conv22"
  type: "Convolution"
  bottom: "conv2"
  top: "conv22"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 0.1
  }
  convolution_param {
    num_output: 16
    kernel_size: 3
    stride: 1
	group: 1
    pad: 1
    weight_filler {
      type: "gaussian"
      std: 0.2108
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}

layer {
  name: "relu22"
  type: "ReLU"
  bottom: "conv22"
  top: "conv22"
}

layer {
  name: "conv23"
  type: "Convolution"
  bottom: "conv22"
  top: "conv23"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 0.1
  }
  convolution_param {
    num_output: 56
    kernel_size: 1
    stride: 1
	group: 1
    pad: 0
    weight_filler {
      type: "gaussian"
      std: 0.25
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}

layer {
  name: "relu23"
  type: "ReLU"
  bottom: "conv23"
  top: "conv23"
}

layer {
  name: "Deconv3"
  type: "Deconvolution"
  bottom: "conv23"
  top: "Deconv3"
  param {
    lr_mult: 0.1
  }
  param {
    lr_mult: 0.1
  }
  convolution_param {
    num_output: 1
    kernel_size: 11
    stride: 3
    pad: 5
    weight_filler {
      type: "gaussian"
      std: 0.001
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
```

**Comment by dxxz** [comment]
Has provide the fix in the internal intel Caffe master, will publish to the github after full cycle validation.

**Comment by HolmesShuan** [comment]
Many thanks. :+1:

**Comment by dxxz** [comment]
I will notice you once the right version is pushed to the github.
