### ISSUE TITLE
Failed to import caffe in jupyter notebook

### ISSUE THREAD

**Issue by cjliux** [intel/caffe#89]
I have successfully import caffe in ipython, but it's quite unnatural for jupyter notebook to raise an error when importing caffe. 

The error message is as follow:

ImportError                               Traceback (most recent call last)
<ipython-input-2-47f087df8a17> in <module>()
      5 #sys.path.insert(0, caffe_root + 'python')
      6 
----> 7 import caffe
      8 # If you get "No module named _caffe", either you have not built pycaffe or you have the wrong path.

/home/cjliux/.local_install/intel_caffe/python/caffe/__init__.py in <module>()
     35 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     36 #
---> 37 from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
     38 from ._caffe import set_mode_cpu, set_mode_gpu, set_device, Layer, get_solver, layer_type_list, set_random_seed
     39 from ._caffe import __version__

/home/cjliux/.local_install/intel_caffe/python/caffe/pycaffe.py in <module>()
     47 import numpy as np
     48 
---> 49 from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
     50         RMSPropSolver, AdaDeltaSolver, AdamSolver
     51 import caffe.io

ImportError: libmkldnn.so: cannot open shared object file: No such file or directory

**Comment by hshen14** [comment]
Would you please specify LD_LIBRARY_PATH to contain mkldnn.so and try again?

**Comment by cjliux** [comment]
Thank you. It works.
