### ISSUE TITLE
How to train GoogleNet V2 using Intel Caffe?

### ISSUE THREAD

**Issue by bage613** [intel/caffe#9]
Hi,
Recently I am doing some research on Intel Caffe. In particular, I want to get performance data with GoogleNet V2 on multi nodes. Can you tell me how to train GoogleNet V2? Concrete commands or wiki url are better. Thank you! BTW, I find there are default_googlenet_v2  and mkl2017_googlenet_v2 in models. Which model I should use?

Best regards,
Xingyi

**Comment by pnoga** [comment]
Hello

Both models should work. If you are using newest Intel CPU (like Broadwell or Xenon Phi) it is recommended to use MKL2017 prototxt.

Right now we are focusing on googlenet v1 in our multinode solution. So your runs on multinode with googlenet v2 will be interesing experiments that we could benefit from. 
What I reccomend: try to use batch 32-128 per node. Try to use bigger Learning Rate with bigger total batch. for total bach 1024 I recommend to use LR= 0.08.

I hope those informations will help you.

**Comment by bage613** [comment]
@pnoga 
Hi pnoga,
Thank you for your help. I will try and share my result later.
