### ISSUE TITLE
malfunctioning compute_image_mean

### ISSUE THREAD

**Issue by cjliux** [intel/caffe#90]
The binary executable `build/tools/compute_image_mean` is malfunctioning, and will abort with bad_alloc

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by hshen14** [comment]
Would you please share your test environment and complete command?

**Comment by cjliux** [comment]
It seems that's not the problem of this executable but the problem of another git repository....
