### ISSUE TITLE
AttributeError: 'LayerParameter' object has no attribute 'dropout_ratio'

### ISSUE THREAD

**Issue by 8Strings82** [intel/caffe#93]
Hello,

I am trying to build up a simple CNN in Python. I design my network directly in Python, using caffe.layers and caffe.params.
After I defined my network, which is containing a Dropout layer (d = L.Droupout(r, dropout_ratio=0.4)), I convert it to prototext ad write in a local file.
When I run my Python script I get the following error:
`Traceback (most recent call last):
  File "/home/gio/workspace_py/GERMANSIGNS/GTSR.py", line 53, in <module>
    fs.write(str(net.to_proto()))
  File "/home/gio/caffe/python/caffe/net_spec.py", line 193, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/gio/caffe/python/caffe/net_spec.py", line 97, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/gio/caffe/python/caffe/net_spec.py", line 162, in _to_proto
    assign_proto(layer, k, v)
  File "/home/gio/caffe/python/caffe/net_spec.py", line 64, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: 'LayerParameter' object has no attribute 'dropout_ratio'`

I am using the intel version of Caffe (version 1.0).
Normally this layer should contain the dropout layer, so I don't understand what the problem is. Does anybody had the same issue?

**Comment by hshen14** [comment]
Caffe.proto does not support dropout_ratio in LayerParameter.
