### ISSUE TITLE
Retraining VGG_ILSVRC_16_layers.caffemodel fails

### ISSUE THREAD

**Issue by MohanaRC** [intel/caffe#94]
I have been trying to retrain the VGG_ILSVRC_16_layers.caffemodel and I keep getting the following error,

I0705 15:55:07.324955 11522 caffe.cpp:155] Finetuning from home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140543368136512:
  #000: ../../../src/H5F.c line 439 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: ../../../src/H5Fint.c line 554 in H5F_is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: ../../../src/H5FD.c line 993 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../../src/H5FDsec2.c line 339 in H5FD_sec2_open(): unable to open file: name = 'home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140543368136512:
  #000: ../../../src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 992 in H5F_open(): unable to open file: time = Wed Jul  5 15:55:07 2017
, name = 'home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: ../../../src/H5FD.c line 993 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../../src/H5FDsec2.c line 339 in H5FD_sec2_open(): unable to open file: name = 'home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
F0705 15:55:07.381656 11522 net.cpp:791] Check failed: file_hid >= 0 (-1 vs. 0) Couldn't open home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel
*** Check failure stack trace: ***
    @     0x7fd2ccc7195d  google::LogMessage::Fail()
    @     0x7fd2ccc736e0  google::LogMessage::SendToLog()
    @     0x7fd2ccc71543  google::LogMessage::Flush()
    @     0x7fd2ccc740ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd2cd20ee78  caffe::Net<>::CopyTrainedLayersFromHDF5()
    @     0x7fd2cd213154  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x40b124  CopyLayers()
    @           0x40c65a  train()
    @           0x4081e0  main
    @     0x7fd2cc006830  (unknown)
    @           0x408b39  _start
Aborted (core dumped)

I am not sure what is causing the error.

I am using Ubuntu 16.04 and Python 2.7
I ran the following statement for the training process
/home/xxx/caffe/build/tools/caffe train -solver /home/xxx/dense_crowd_counting/models/dcc_crowdnet/solver.prototxt -weights home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel

**Comment by hshen14** [comment]
Would you please paste the solver and train_val prototxt to reproduce the issue?

**Comment by fzou1** [comment]
Please check if the privilege of the weight file can be read by the user by "ls -l" command below:
ls -l home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel

**Comment by hshen14** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by Sally-fyk** [comment]
I have the same problem. Have you solved it?

**Comment by fzou1** [comment]
I believe it's caused by typo of weight file path. it should have "/" before "home" in the path.
    home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel

please have a check.
