### ISSUE TITLE
Is there a direct way to configure threads count used by OpenMP inside MKL layers?

### ISSUE THREAD

**Issue by sergboec** [intel/caffe#99]
Is there any way to configure threads count for OpenMP not with environment variable?

**Comment by jgong5** [comment]
May I know why you ask the question?

**Comment by sergboec** [comment]
@jgong5  i want to run multiple binaries using intel caffe on the same machine. 
And i want to give to one of them more "free cores" than to the rest of others.

**Comment by jgong5** [comment]
Run multiple caffe via mpirun?

**Comment by sergboec** [comment]
@jgong5 i'm afraid that's not a solution, cause i have not a "clear" caffe but, caffe linked into another binary

**Comment by jgong5** [comment]
Oh, I didn't propose a solution but just wanted to know more how you are running multiple Caffe on a single node. Why can't you set different environment variable to different Caffe processes?

**Comment by sergboec** [comment]
> Why can't you set different environment variable to different Caffe processes?
@jgong5 i can, but i don't want to solve the problem that way. Nevertheless i will implement solution with environment variable, if there is no other way.

**Comment by sergboec** [comment]
Ok. Solution with enviroment varialable worked for me
